### ISSUE TITLE
Precision of Period@start

### ISSUE THREAD

**Issue by baconz** [Dash-Industry-Forum/DASH-IF-IOP#100]
Period start times (for period indexes > 0) need to precisely match up with the duration of the previous period. If they do not the player may fall into a loop searching for a segment in the wrong period.

Since @start can only be represented as a PT, we are forced to use floating point arithmetic for the start time calculation. The manifest generator needs to be aware of how each client is going to handle floats, and generate appropriate start times. For example, our javascript manifest truncates the start times at 16 digits.

Ideally we could represent durations as PTs OR normalized seconds, where @timescale is applied to the value. This would be a pretty big change to the spec, and gets especially hairy when you consider varying timescales across SegmentBases. It would require a @timescale on MPD and/or Period, but it would eliminate this floating point madness. To be clear, I'm suggesting that both of these would be valid:

```
<Period start="1234" timescale="10">
<Period start="PT123.4S">
```

Do you know if this has every been proposed or discussed? It looks like somebody made reference to the idea of non-PT durations in https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/54.

**Comment by haudiobe** [comment]
addressed in version 3.32
