### ISSUE TITLE
Player issue

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#104]
Submitter: Richard Pialat
Email: richard.pialat@globecast.com
Tested with version 1.4.0 and 2.2.0

Firefox v48 / Windows 7
When we seek the image remains frozen and the seek never occurs
This works with other players

Firefox v48 / MAC OS
Seek works but there are artifacts when play resumes then after a short while video is OK
This works on Chrome

Tests can be conducted with the following video:
http://cdn-vod-dash.globecast.tv/vod/HBS-2010-2011/video5s/dash/video5s.mpd

Thank you

**Comment by haudiobe** [comment]
Bug forwarded to dash.js!

**Comment by wilaw** [comment]
@haudiobe  - what is the corresponding dash.js issue?
