### ISSUE TITLE
Trick Mode for Live

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#107]
Yes that’s correct.

Thanks
Karishma

From: Stockhammer, Thomas [mailto:tsto@qti.qualcomm.com] 
Sent: Friday, September 16, 2016 1:32 PM
To: Karishma Bagga kbagga@adobe.com; Iraj Sodagar irajs@microsoft.com; wilaw@akamai.com; waqar.zia@hotmail.com zia@nomor.de
Subject: RE: Live Trick play test vector

OK! We will add this to the list! 

I believe you want to have test vectors for which 1 I frame = 1 segment as well as some for which you package multiple ones in a segment. 

Thomas

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
From: Karishma Bagga kbagga@adobe.com 
Date: 9/16/16 09:48 (GMT+01:00) 
To: "Stockhammer, Thomas" tsto@qti.qualcomm.com, Iraj Sodagar irajs@microsoft.com, wilaw@akamai.com, "waqar.zia@hotmail.com" zia@nomor.de 
Subject: RE: Live Trick play test vector 

Hi Thomas,

Yes it’s mostly scrolling back in the DVR window of live stream and then doing a forward from there; and the playback rate will switch to 1 once we hit the live edge.
So 5 seconds behind would do too.

Best
Karishma

From: Stockhammer, Thomas [mailto:tsto@qti.qualcomm.com] 
Sent: Friday, September 16, 2016 1:14 PM
To: Karishma Bagga kbagga@adobe.com; Iraj Sodagar irajs@microsoft.com; wilaw@akamai.com; waqar.zia@hotmail.com zia@nomor.de
Subject: RE: Live Trick play test vector

Karishma,

I understand the I-frame only, but how is it used? In time-shift mode? You do some scrolling back and forth?
Do you need to have it at the live edge? Or more like with 5 seconds behind?

The generation of test vectors should be relatively easy, but I wanna cover the use case in order to make sure we do it the right way.

Thanks

Thomas

From: Karishma Bagga [mailto:kbagga@adobe.com] 
Sent: Friday, September 16, 2016 9:23 AM
To: Stockhammer, Thomas tsto@qti.qualcomm.com; Iraj Sodagar irajs@microsoft.com; wilaw@akamai.com; waqar.zia@hotmail.com zia@nomor.de
Subject: RE: Live Trick play test vector

Hi Thomas
I want a live dash stream with a separate adaptation set for iframe only media segments.
There are too many customers asking for the ability to do live trick play and it’s getting tough to get hold of any test content.

Thanks in advance
Karishma

From: Stockhammer, Thomas [mailto:tsto@qti.qualcomm.com] 
Sent: Friday, September 16, 2016 12:48 PM
To: Iraj Sodagar irajs@microsoft.com; Karishma Bagga kbagga@adobe.com; wilaw@akamai.com; waqar.zia@hotmail.com zia@nomor.de
Subject: RE: Live Trick play test vector

Karishma,

Can you explain the exact feature? You want to use a low temporal resolution distributed separately? 

We have multiple options, so please define the feature use case and I add it to the live tf!

We have a call later today!

Thanks

Thomas

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
From: Iraj Sodagar irajs@microsoft.com 
Date: 9/16/16 09:14 (GMT+01:00) 
To: Karishma Bagga kbagga@adobe.com, "Law, Will" wilaw@akamai.com, "waqar.zia@hotmail.com" zia@nomor.de, "Stockhammer, Thomas" tsto@qti.qualcomm.com 
Subject: Re: Live Trick play test vector 

Adding Waqar & Thomas.
Karishma,
We will review & consider this. 
BR
Iraj
From: Karishma Bagga
Sent: Thursday, September 15, 11:10 AM
Subject: Live Trick play test vector
To: Law, Will, Iraj Sodagar
Hi Will/Iraj This is regarding trick play test vectors from dash-if. We have been struggling to get any live trick play test vector. As am not sure if there's any encoder which currently produces such a content, I was looking for some help from dash-if around it. I even wrote to Tobbe as I could not get live sim to do it for us too. Do we have any plans of adding live trick play test vectors? We have more and more customers asking for trick play support now. Thanks in advance Karishma

**Comment by KarishmaBagga** [comment]
Do we have an ETA for this?
TIA
Karishma

**Comment by KarishmaBagga** [comment]
Hi
Pinging again to check if we have any sense of timeline by which this could be available?
TIA
Karishma

**Comment by KarishmaBagga** [comment]
I see the issue closed. Do we have a test vector available now?

**Comment by wilaw** [comment]
See http://testassets.dashif.org/#feature/details/586fb3879ae9045678eab58b which lists 5 test vectors.

Cheers
Will
