### ISSUE TITLE
DASH-IF IOP and Test/Conformance

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#108]
The DASH-IF IOPs mention conformance and test, but no proper explanation and reference is provided to our test assets. There should be half a page on each
- test cases and test vectors
- conformance software
- reference client

**Comment by waqarz** [comment]
In addition to the IOP doc, both software and test docs need update.

A question for IOP group, would we continue to maintain test doc in the presence of the test website?

**Comment by haudiobe** [comment]
addressed in v4.12
