### ISSUE TITLE
Segment Number Calculation

### ISSUE THREAD

**Issue by joywelt** [Dash-Industry-Forum/DASH-IF-IOP#111]
I noticed that there's a small bug in IOP v3.3 (also in the latest v3.3.x in groupspace):

in section 4.3.3.3.1.(P42), for period 3, the `k2` should be calculated as:

`ceil((PDURATION-PSTART3)/SDURATION1)`

instead of

`ceil((PSTART3-PDURATION)/SDURATION1),`

as the latter is a negative value, and it's inconsistent if compared to calculation for period 1 and 2.

**Comment by haudiobe** [comment]
Addressed in v3.34
