### ISSUE TITLE
Inconsistent spelling for schemeIdUri

### ISSUE THREAD

**Issue by kqyang** [Dash-Industry-Forum/DASH-IF-IOP#112]
The spelling for schemeIdUri is not consistent in DASH-IF-IOP document. There are three different variants: schemeIdUri, schemeIdURI, schemeIDURI.

The inconsistency is also observed in DASH spec (23009-1:2014).

Here are a few statistics:

In IOP v3.3:
- schemeIdUri appears 25 times
- schemeIdURI appears 8 times
- schemeIDURI appears 1 time

In the DASH spec:
- schemeIdUri appears 56 times
- schemeIdURI appears 2 times
- schemeIDURI appears 1 time

schemeIdUri is what is used most frequently and in all the XML schemas. I assume the other spellings are typos. Can we fix it?

**Comment by haudiobe** [comment]
Thanks! Addressed in v3.96!

**Comment by joeyparrish** [comment]
The inconsistent case is back in v4.2 of the IOP, and it seems that it has never been corrected in the spec text, either.  The 2014 spec and 2015 corrigenda both appear to be case-inconsistent as well.

Can we get both the IOP and the spec fixed?
