### ISSUE TITLE
[UHD] Editorial fixes to DASH-IF-IOP-v3.95-clean.docx

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#113]
In Section 10.2.2.1.    Constraints on Picture Formats:
- Space missing at the end of sentence: 
  for color sub-sampling.The bit ==> for color sub-sampling. The bit 
- Check: 
  Chroma Format and 4:2.0 ==> Chroma Format and 4:2:0
- Check: 
  See Section xxx for details about HEVC encoding. ==> See Section 10.2.2.2 for details about HEVC encoding.

**Comment by haudiobe** [comment]
Thanks! Addressed in v3.96!
