### ISSUE TITLE
comments on HDR for DASH-IF-IOP-v3.95-clean.docx 

### ISSUE THREAD

**Issue by emauena** [Dash-Industry-Forum/DASH-IF-IOP#115]
The current version of the document only specifies interoperability points that are essential for delivering HDR content, that is, it does not consider to test any metadata scheme. Ericsson believes that readers may find confusing to mention and refer the generic way to carry metadata information through HEVC, especially if the verification of the test vectors excludes them.

SEI (and CRI) messages is a mechanism in HEVC to carry (or map) metadata, this means that it would be relevant to mention or specified them, only if, DASH-IF decides to consider the inclusion of specific metadata schemes for HDR. Further, it may be proper to define how to carry the specific metadata information at HEVC bitstream level only if DASH-IF decides to evaluate the performance of these schemes with test vectors. At the moment, the latest version of this document let the SEI messages undefined and this may cause unnecesary confusion.

Note that specifiying metadata presence at higher layer in the DASH protocol is another issue.

Ericsson suggest to have the following text in the document:

Note that optional metadata may be present in the form of SEI messages as defined in ITU-T H.265 /ISO/IEC 23008-2:2015 [19].

1.1.1.1.	Bitstream Requirements and Recommendations
A bitstream conforming to the HEVC HDR PQ10 media profile shall comply with the Main Tier Main10 Profile Level 5.1 restrictions, as specified in Recommendation ITU-T H.265 / ISO/IEC 23008-2 [19].
In addition the requirements in section 10.2.2.2 apply, except that this profile requires the use of Recommendation ITU-R BT.2020 [74] non-constant luminance colorimetry and SMPTE ST 2084 [71].
SMPTE ST 2084 [71] usage shall be signaled by setting colour_primaries to the value 9, transfer_characteristics to the value 16 and matrix_coeffs to the value 9.

1.1.1.2.	Receiver Requirements
Receivers conforming to the HEVC HDR PQ10 media profile shall support decoding and displaying HEVC HDR PQ10 bitstreams as defined in section 10.3.2.2.
No additional processing requirements are defined, for example processing of SEI messages is out of scope.

/Mauricio

**Comment by haudiobe** [comment]
I do not understand the comment. All proposed text is already present exactly as is.

**Comment by haudiobe** [comment]
New Candidate Proposal: The bitstream may contain SEI messages as permitted by the Recommendation ITU-T H.265 / ISO/IEC 23008-2:2015 [19]. Details on these SEI messages are specified in Recommendation ITU-T H.265 / ISO/IEC 23008-2 / Annex D. SEI message may for example support adaptation of the decoded video signals to different display capabilities or more detailed content description, in particular **_those specified in Recommendation ITU-T H.265 / ISO/IEC 23008-2 / Annex D in relation to HDR._** Other SEI Messages defined in ITU-T H.265 / ISO/IEC 23008-2 / Annex D may be present as well.

**Comment by haudiobe** [comment]
Candidate Proposal accepted with reservations: "Qualcomm states reservation on the process and believes that this unnecessarily delays publication by several weeks. The problem that was raised is not understood or should have been raised much earlier."
