### ISSUE TITLE
Question for clarification on mandate of @indexRange/RepresentationIndex 

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#117]
Section 3.2.1:

"Indexed Media Segment [4], clause 6.3.4.4: In this case either the @indexRange attribute shall be present or the RepresentationIndex element shall be present. Only a single sidx box shall be present."

Indexed Media Segment can be OnDemand or live profile, does the mandate above only apply to OnDemand?

**Comment by haudiobe** [comment]
Only for On-Demand. So clarify this in the the IOP. Editorial! Address in version before publication.

**Comment by haudiobe** [comment]
Addressed in v3.96! Thanks
