### ISSUE TITLE
Annotation for trick modes

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#118]
We have at least 2 test cases for trick modes;

- Low-frame rate version.
- Low resolution "thumbnail" representation.

Do we need to add some signalling for annotation of different use cases?

**Comment by haudiobe** [comment]
We should say
1) There may be multiple trick mode adaptation sets
2) There should be a clear signalling on the properties of the trick mode AS.
- framerate (if differentiating)
- codingDependency
- spatial resolution (thumbnail)
- maxPlayoutRate
- duration attribution
Editorial for the publication. Use the above for test vector generation.

**Comment by haudiobe** [comment]
Even of low bandwidth and I frame, we run into Adaptation modes, bandwidth is also important, Will add as well.

**Comment by haudiobe** [comment]
adressed in v3.96! Thanks
