### ISSUE TITLE
Relation between width/height with minWidth/minHeight

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#122]
IOP says: "The attributes @maxWidth and @maxHeight should be used such that they describe the target display size. This means that they may exceed the actual largest size of any coded Representation in one Adaptation Set."

- Does this mean width/height adjusted by aspect ratio? This is not mentioned in the MPEG DASH spec e.g. "@minWidth: specifies the minimum @width value in all Representations in this Adaptation Set. This value has the same units as the @width attribute."
- Do we need to also specify relation between width/height with minWidth/minHeight?
- Currently conformance software does not allow width < minWidth. here: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/92#issuecomment-275126933

**Comment by haudiobe** [comment]
(Thomas) add this to v4.1
added to v4.03 as follows:"The attributes @minWidth and @minHeight should not be present. If present, they may be smaller than the smallest @width or smallest @height in the Adaptation Set."
added v4.03
