### ISSUE TITLE
[UHD] Update table reference for Colour Primaries and Transfer Characteristics

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#123]
Change:

-	The Color Primaries and Transfer Function may be signalled. If signalled, 
o	an Essential or Supplemental Descriptor shall be used to signal the value by set-ting the @schemeIdUri attribute to urn:mpeg:mpegB:cicp: Colour-Primaries and urn:mpeg:mpegB:cicp:TransferCharacteristics as defined ISO/IEC 23001-8 [49] and the @value attribute according to Table 4 of ISO/IEC 23001-8 [49]. The values shall match the values set in the VUI.

To

-	The Color Primaries and Transfer Function may be signalled. If signalled, 
o	Essential or Supplemental Descriptors shall be used to signal the value by setting the @schemeIdUri attribute to urn:mpeg:mpegB:cicp:ColourPrimaries and urn:mpeg:mpegB:cicp:TransferCharacteristics, respectively, as defined ISO/IEC 23001-8 [49] and the @value attribute according to Table 2 and Table 3 of ISO/IEC 23001-8 [49], respectively. The values shall match the values set in the VUI.

![image](https://cloud.githubusercontent.com/assets/3089913/22339597/d395c358-e3ea-11e6-9fda-54ae8a11c853.png)

**Comment by rdoherty0** [comment]
Suggestion to reference the Table Names rather than the Table numbers, as Table numbers change between editions.

**Comment by haudiobe** [comment]
added to v4.01
