### ISSUE TITLE
Clarification about AudioChannelConfiguration

### ISSUE THREAD

**Issue by TheModMaker** [Dash-Industry-Forum/DASH-IF-IOP#124]
The IOP guidelines don't explicitly talk about this, but the [Identifiers](http://dashif.org/identifiers/audio-source-data/) page does as does the DASH spec itself (sec. 5.8.5.4).  The scheme `urn:mpeg:dash:23003:3:audio_channel_configuration:2011` for `AudioChannelConfiguration` contains confusing text.  The Identifiers page says that:

> This URI is used to indicate the channel configuration. The value is the value as defined for **OutputChannelPosition** in ISO/IEC 23001-8 [4].

However, in the ISO/IEC 23001-8 spec, the OutputChannelPosition (table 7) doesn't seem right. It is used as an index to tell where the speaker should be.  Some people seem to think this is the number of channels.  The scheme `urn:mpeg:mpegB:cicp:ChannelConfiguration` says that it contains the number of channels.

Is this supposed to say `ChannelConfiguration in ISO/IEC 23001-8` (with table 8)?  That would make more sense since it can be used to determine the number and position of the speakers.  Or is it supposed to be simply the number of channels?

**Comment by haudiobe** [comment]
Addressed on DASH-IF Web page
