### ISSUE TITLE
Audio channel config

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#126]
DASH-IF-IOP 4.0:

6.3.3.2.	ISO/IEC 23009-1 audio data
With respect to the audio metadata, the following elements and attributes from ISO/IEC 23009-1 are relevant:
•	the @audioSamplingRate attribute for signaling the sampling rate of the audio media component type in section 5.3.7 of ISO/IEC 23009-1
•	the AudioChannelConfiguration element for signaling audio channel configura-tion of the audio media component type.in section 5.3.7 of ISO/IEC 23009-1.

When refering to section 5.3.7 of 23009-1, are we recommending using audio channel config scheme of 23003-3 or the one in 23001-8 (cicp)? it's not clear. We need to be more explicit.

**Comment by haudiobe** [comment]
added to v4.06
