### ISSUE TITLE
[UHD] Several Comments on Dolby Vision

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#128]
I reviewed the text in UHD-to-IOP-v1s-2-3-2017-DV and included my comments and suggestions in the attached.

My review conclusion is that there are a lot of issues, technical and editorial, particularly in the file format encapsulation and signalling designs.

Below is a summary of a subset of the issues:
-	For the dual stream mode, a lot of deign details are for having both the BL and EL streams in one track. However, how are they multiplexed in this case? There is no way that the bitstream carried in the track can be conforming unless layered HEVC syntax is used, including using layer ID greater than 0 for EL NAL units. In addition, how can the NAL units of the BL and EL be identified/separated and sent to their respective decoders?
-	The single stream mode specified in 10.5 seems to be a mystery: What is the difference between the bitstream of this mode and a normal HEVC bitstream?
-	The bitstream requirements say only HEVC, but there are lots of AVC specific designs for file format and other signalling aspects. All AVC stuff should be removed as they are useless for the two IOPs being defined.
-	There are a lot of vague and inaccurate wordings that needs to be clarified. Example: “Content shall only be authored claiming conformance to this IOP if a client can properly play the content.”
-	There are quite a few incorrect cross-references, including references to non-exiting sections.
-	There are places contradicting each other. For example, for the dual streaming mode, some place says that two or more adaptation sets (hence at least two tracks) must be used while many other places talk about using one track only.
-	The terms in A.1.1.1 are defined but are not used in the document at all.

[UHD-to-IOP-v1s-2-3-2017-DV yk00.zip](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/files/838895/UHD-to-IOP-v1s-2-3-2017-DV.yk00.zip)

**Comment by rdoherty0** [comment]
Comments reviewed and addressed in UHD subgroup.

**Comment by haudiobe** [comment]
Bug is addressed by UHD TF and can be closed
