### ISSUE TITLE
Clarification of Location element and redirect

### ISSUE THREAD

**Issue by TobbeEdgeware** [Dash-Industry-Forum/DASH-IF-IOP#131]
Some service providers use HTTP 30X redirect in the Manifest response to introduce a session ID in the URL. This redirect address is typically recognized by the player and used as the manifest in the processing for generating an implicit BaseURL for segment requests. It is also used for future manifest requests.

However, in some cases, there is no way for the client to acquire the redirection URL. This is in particular the case in the IE11 and Edge (before Anniversary Edition) browsers. In this case, we need another solution.

One possibility is to use the Location@MPD element. That provides the address where the MPD is located. One plausible interpretation is that it should result in the same behavior as an HTTP 30X redirect, which would then provide a complete redirect solution on the manifest level. This is also how it has been interpreted in implemented by some players like Shaka-player and Theoplayer. However, it is not very clear from either the DASH spec 23009-1 or the DASH-IF IOP document that \<Location\> shall be used implicitly for segments since the text only talks about Manifest. The dash.js reference player currently, does not use the \<Location\> element for segments, so there is no way to do redirect on the browsers mentioned above, and an issues has been filed to fix that https://github.com/Dash-Industry-Forum/dash.js/issues/1887, but it would be nice to have support for that from DASH-IF before implementation.

It may also be worth clarifying the priority order or redirection. A natural order is:

1 The original manifest URL is the starting point, and provides an implicit BaseURL
2 a 30X HTTP redirect replaces the original manifest URL in all future processing
3 a Location@MPD value replaces the manifest URL from step 1 or 2.
4 a relative baseURL will add to whatever URL was results from the the first 3 steps.

The only case that remains is an absolute BaseURL at the top level. This must come before the Location according to the Schema, so the question is whether the Location should override it or not.
That is pretty strange construction though, so I'm not sure if we need to have a "correct" interpretation in this case.

I propose to add clarifying text on this to the next IOP version.

**Comment by TobbeEdgeware** [comment]
The slides were updated to the files area on GroupSpaces on May 19 2017.

**Comment by haudiobe** [comment]
added to v4.2.1
