### ISSUE TITLE
DRM Multi-key

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/DASH-IF-IOP#134]
When DASH content is protected by multiples keys (one for video and one for audio typically), guidelines are not clear on the expected DRM client-DRM server behavior. Various implicit assumptions and/or consequences of IOP statements are not sufficiently explicit and may lead to misinterpretation in Section 7.7.
Please see CR at http://files.groupspaces.com/dashif/files/1952788/IOP+4.0+-+CR+-+multi-key+-+v3.docx

**Comment by sandersaares** [comment]
I believe this has been resolved in IOP 4.1.

**Comment by lpiron** [comment]
Yes, agree, this can be closed.
