### ISSUE TITLE
Adaptation Set Switching

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#135]
Submitter: Oliver Woodman
Email: olly@google.com
Section 3.8 contains the following:

As an example, a content author may signal that seamless switching across an H.264/AVC Adaptation Set with AdaptationSet@id=”h264” and an HEVC Adaptation Set with AdaptationSet@id=”h265” is possible by adding a Supplemental Descriptor to the H.264/AVC Adaptation Set with @schemeIdUri set to urn:mpeg:dash:adaptation-set-switching:2016 and the @value=”h265” and by adding a Supplemental Descriptor to the HEVC Adaptation Set with @schemeIdUri set to urn:mpeg:dash:adaptation-set-switching:2016 and the @value=”h264”.

According to the DASH spec, however, AdaptationSet@id has type xs:unsignedInt. Hence the example appears to be in violation of the spec. Can the example be updated to use integer AdaptationSet@id values?

**Comment by ojw28** [comment]
Same as https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/136 (so can be duped).

**Comment by haudiobe** [comment]
added to v4.04
