### ISSUE TITLE
Key Hierarchy default_KID

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/DASH-IF-IOP#142]
Section 7.5.3.4 (key hierarchy) is not clear on which key is associated to the default_KID as in this case, this is not the content key used for encrypting content that are referenced but the key used for encrypting these content keys. 
Proposed clarifications are given in http://files.groupspaces.com/dashif/files/1981927/DASH-IOP-CRxxxx-rev0.doc

**Comment by haudiobe** [comment]
added to v4.07
