### ISSUE TITLE
Multi-Track describes @par usage incorrectly - it is actually DAR

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#143]
In table 1 of http://dashif.org/wp-content/uploads/2014/12/MultiTrack-DASH-IF-IOP-v0.9.pdf, we have a row for `@par` where the description says:

> shall be present, if the picture aspect ratio is a differentiating parameter
in the MPD

However, `@par` actually refers to the **display** aspect ratio, not the picture aspect ratio!

This is due to an unfortunate naming error in DASH - the extended description for the attribute makes it clear that really it talks about the display aspect ratio. Perhaps there are other places that this error also "infects"? I have not checked.

**Comment by haudiobe** [comment]
added to v4.07
