### ISSUE TITLE
Multi-Track has conflict in whether default role is main or alternative

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#144]
In http://dashif.org/wp-content/uploads/2014/12/MultiTrack-DASH-IF-IOP-v0.9.pdf 3.10.4.2 says:

> Main content is signaled by using the Role descriptor with Role scheme as defined by MPEG-DASH in ISO/IEC 23009-1, 5.8.5.5, urn:mpeg:dash:role:2011 with value set to main. Alternative content is signaled by using the Role descriptor with Role scheme as defined by MPEG-DASH in ISO/IEC 23009-1, 5.8.5.5,
urn:mpeg:dash:role:2011 with value set to alternative. If an Adaptation Set does not include either of the
two signals, it is assumed to be main content.

i.e. default is main.

However, table 1 says for `Role` element:

> If not present, the role is assumed to be alternate

These two statements appear to me conflicting.

**Comment by haudiobe** [comment]
added to v4.07
