### ISSUE TITLE
Multi-track does not recognize "subtitle" role on subtitle tracks, whereas IOP does

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#145]
IOP 4.0 says:

> Subtitle Adaptation Set: An Adaptation Set that contains visual overlay information to be 35 rendered as auxiliary or accessibility information. Such an Adaptation Set is identified by 36 @mimeType="application/mp4", a Role descriptor with @schemeIdUri=" 37 urn:mpeg:dash:role:2011" and @value="subtitle" and, an @codecs 38 parameter as defined in Table 20or "application/ttml+xml".

A "subtitle" role is therefore required to be recognized as a subtitle adaptation set.

However, the multi-track CR does not list "subtitle" at all when describing roles that apply to text tracks.

I can see multiple interpretations here. Perhaps the "subtitle" role requirements is obsolete and unnecessary? Should all text tracks be treated as subtitle tracks by default? However, the CR does not really modify 3.2.13 so it is something of a conflict between the text to be added and the text already in IOP.

Alternatively, is this just an accidental omission?

It is not currently clear what the intent is with regard to usage of the "subtitle" descriptor on text tracks. Multi-track should make it more explicit whether it is to be used or not to be used, and if it is to be used what its intended purpose is.

**Comment by haudiobe** [comment]
added to v4.07
