### ISSUE TITLE
Typo section 9.4.2.3 Defintion

### ISSUE THREAD

**Issue by rdoherty0** [Dash-Industry-Forum/DASH-IF-IOP#150]
For DASH-IF IOPv4.0 (and v4.09) section 9.4.2.3, the third "Content" paragraphs states:

"Content may be authored claiming conformance to DASH-IF multichannel extension with AC-4 DASH-IF multichannel extension with Dolby TrueHD"

This is a cut and paste error, please remove the extra text "multichannel extension with Dolby TrueHD" text.

**Comment by haudiobe** [comment]
editorial - do it before 4.1 publication

**Comment by haudiobe** [comment]
addressed in v4.091
