### ISSUE TITLE
Issue of initialization range for on-demand content

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#154]
An issue has been reported by Exoplayer team: https://github.com/Dash-Industry-Forum/Test-Vectors/issues/66

Context of this: https://github.com/google/ExoPlayer/issues/605

DASH-IF IOP currently does not mandate Initialization range for on-demand, do we need to change this?

**Comment by haudiobe** [comment]
addressed in v4.12
