### ISSUE TITLE
MPEG LS 29n16757 on 14496-15 Visual Sample Entry width and height

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#156]
- ISO/IEC 14496-15 specifies that the width and height of the visual sample entry is the exact width and height of the picture in the sample associated with this sample entry for non-scalable AVC and HEVC tracks, and the maximum width and height for tracks carrying scalable bitstreams.

- This implies that storing a single layer AVC or HEVC stream with resolution changes requires creating multiple visual sample entries; this also imposes usage of multiple initialization segments for fragmented ISOBMFF-based adaptive streaming.

**Comment by waqarz** [comment]
Resolution:

- It should be noted that DASH-IF conformance cannot check the track width/height consistency below the file format level.
- I am not aware of any test case or feature that requires changing resolution _within a single period_. Hence if there is any change of a resolution in a test vector, it would be accompanied by a new init segment, which would avoid any issue in the first place.

The issue can be considered resolved.

**Comment by haudiobe** [comment]
What about bitstream switching? Waqar will check

**Comment by waqarz** [comment]
Some HEVC vectors found to have bitstreamswitching, tracked here: https://github.com/Dash-Industry-Forum/Test-Vectors/issues/67
