### ISSUE TITLE
minimum buffer time

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#158]
Submitter: Alexandre Gabriel
Email: alexandre.dasilvapratasgabriel@tno.nl
In section 3.2.8 it is unclear in the 2nd bullet point, line 23 ("The minimum buffer time provides..."), what the delay is. It says the time and the delay are PT+MBT although it makes more sense that the delay should be MBT. The bullet point has confusing language. This sentence (lor to the effect) also appears in pg60 line 22 and pg58 line 12.

**Comment by sandersaares** [comment]
As promised in our last call, I did a review of this point as I had recently run into the topic, as well. I have no further requests for clarification to add here.

**Comment by haudiobe** [comment]
Thanks Sander
