### ISSUE TITLE
Problems with requiring cenc:default_KID in communications between client and server

### ISSUE THREAD

**Issue by kqyang** [Dash-Industry-Forum/DASH-IF-IOP#159]
The issue is initially brought up in https://github.com/google/shaka-player/issues/1107.

DASH-IF-IOP v4.1 mentions

> 7.7.9. Client Interactions with DRM Systems
>
> The client interacts with one or more DRM systems during playback in order to control the decryption of content. Some of the most important interactions are:
> 1) Determining the availability of media keys.
> 2) Requesting the DRM system to acquire media keys.
> 
> In both of these interactions, the client and DRM system use the default_KID as an abstract mechanism to communicate information regarding the capability to decrypt adaptation sets that use a particular default_KID. A DRM system may also make use of other media keys in addition to the one signalled by default_KID (e.g. in key derivation or sample variant schemes) but this SHALL be transparent to the client, with only the default_KID being used in communications between the client and DRM system.
>
> A client SHALL determine the required set of media keys based on the default KIDs signalled in the manifest for the adaptation sets selected for playback.

There are two problems with the above paragraph:

1. It implies that `default_KID` is required, although multiple places in the document describes the attribute as optional:

> 7.3. Base Technologies Summary
The default_KID information may also appear in the MPD

> 7.7.2. MPD Content Protections Constraints 
The ContentProtection Descriptor for the mp4protection scheme should contain the optional attribute cenc:default_KID. 

2. According the above paragraph, if a new key needs to be acquired from license server, it must be signaled with a different value of default_KID. Since default_KID in mpd maps to the default_KID field in tenc box, the initialization segment has to be updated too. 

This requires the indication of key id using tenc box and essentially disallows the indication of key id using sbgp sgpd with seig in media segments (see 7.4.1) for regular key rotation (non hierarchical key).

This also requires the usage of multiple periods for each key rotation period, carrying different initialization segments, which does not seem right.

I think we should rephrase this paragraph:

- Mention explicitly that default_KID is optional in manifest
- With regular key rotation, we should allow both cases:

  1. Use the same initialization segment throughout. The initialization segment, including default_KID stays the same even if key rotates. cenc:default_KID should not present in the manifest. Use sbgp sgpd with seig in media segments to indicate the key id (See DASH-IF-IOP v4.1 7.4.1). There is no need to use separate periods when key rotates as neither initialization segment nor cenc:default_KID changes.

  2. Update cenc:default_KID and thus initialization segment whenever key rotates. A separate period needs to be created when key rotates. default_KID indicates the KID in the representations contained in the period.

**Comment by sandersaares** [comment]
> 7.7.2. MPD Content Protections Constraints
> The ContentProtection Descriptor for the mp4protection scheme should contain the optional attribute cenc:default_KID.

I note that this confusing use of the word "optional" was already supposed to be addressed by https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/134 but due to what appears to be an error during document merging still remains in IOP.

**Comment by tinskip** [comment]
We have agreed during the F2F that the mechanism by which we are currently doing "external" (requiring licensing) key rotation is not interoperable, and that an interoperable mechanism exists (multi-period).  Google can of course continue to do key rotation in a manner not documented as a IOPs, but probably ought to implement the recommended solution.

Agreed that default_KID probably ought to be required.

**Comment by kqyang** [comment]
Does it mean that, to be spec complaint, for external key rotation, we'll have to update the key id in tenc box, update the init segment, instead of updating the key id using sbgp sgpd with seig boxes? In another word, sbgp sgpd with seig should only be used to signal internal key rotation, which does not need external license requests?

**Comment by haudiobe** [comment]
Closed at f2f#17
