### ISSUE TITLE
Reference to Indexed Media Segment

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#162]
In DASH 3rd edition Sections 6.3.4.3 and 6.3.4.4 were renumbered to 6.3.4.4 and 6.3.4.5. Only one place in IOP guideline we refer to 6.3.4.4 (in section 3.2.1), could this cause confusion (potentially not since Section name is also mentioned; but then the names are quite similar)

**Comment by haudiobe** [comment]
addressed in v4.12
