### ISSUE TITLE
Correct misleading "optional" description of default_KID in 7.7.2

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#163]
> 7.7.2. MPD Content Protections Constraints
> The ContentProtection Descriptor for the mp4protection scheme should contain the optional attribute cenc:default_KID.

The word "optional" should be removed here and the "should" changed into "shall".

The reason is that `cenc:default_KID` is actually not in any way optional in any of the interoperable scenarios. Some other parts of the content protection logic also assume it exists in encrypted content.

This was already supposed to be addressed by #134 but due to what appears to be an error during document merging still remains in IOP.

**Comment by haudiobe** [comment]
addressed in v4.12
