### ISSUE TITLE
Specify that UTCTiming relative URLs are relative to MPD

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#164]
UTCTiming allows time source URLs to be specified but DASH does not go into detail about it.

Relative URLs are valid URLs and should be supported. But relative to what? The obvious answer is: relative to the thing the UTCTiming is attached to! So relative to the MPD.

I therefore propose the treatment of relative UTCTiming URLs to be defined as relative to the MPD in IOP, to avoid players treating them as relative to the page hosting the player (which makes no sense as a base for relative logic for something defined in the content itself).

Related: https://github.com/Dash-Industry-Forum/dash.js/issues/2333

BaseURL and Location should also be considered when specifying this in detail, most likely.

**Comment by haudiobe** [comment]
addressed in v4.12
