### ISSUE TITLE
[LEAP] Leap Second - Media Timing

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#167]
This

"	• Segment durations are the span of real time (including leap seconds) that elapses between the availability of consecutive Segments”

is not very clear and may not make sense.  

Durations are just that, durations; if I tell you something lasts for 30 minutes and 15 seconds, it lasts for 30*60+15 seconds. That’s it. Leap seconds are an artefact of wall-clocks, not stop-clocks.

In general, do not embed transient characteristics of when something was done once into the media-related info. Sure, have UTC timestamps be UTC timestamps, but durations should reflect the durations of the media. If I take a set of segment files and re-broadcast them later, sure I will re-base availability times, but I shouldn’t havr to do anything to the media timing.

**Comment by sandersaares** [comment]
Is it the word "availability" the problematic one you see? How about replacing that word with "MPD start time" instead?

**Comment by sandersaares** [comment]
Will summarize this and other received comments under #161.

**Comment by sandersaares** [comment]
Closing this as duplicate, discussion under https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/161
