### ISSUE TITLE
Clarification needed for RepresentationIndex

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#171]
IOP document refers to "external Representation Index", but this is not defined.
This term is not used in DASH spec.
If we only consider "Representation Index", this segment format is only defined in the context of MPEG-2 TS in subclause 6.4.6.3 of DASH spec. A definition is needed for Representation Index for ISO BMFF.

**Comment by waqarz** [comment]
Issue applicable to DASH-IF IOP v4.1

**Comment by haudiobe** [comment]
MPEG does not define Representation Index for ISO BMFF, the Segment Index is included in the file and not separate.
This was supposed to be resolved, but it is not properly done.

Questions:
1)	Who uses external Representation Index?
2)	If used, any issues?
3)	If not used, planning to use?

I recommend that we remove this tool for now in v4.2 and send and LS to MPEG that this is unclear and MPEG should resolve this.

**Comment by haudiobe** [comment]
I recommend that we remove this tool for now in v4.2 and send and LS to MPEG that this is unclear and MPEG should resolve this.
Agree to proposal - Remove tool, and send LS to MPEG - add a note and also keep it in the test data base
This feature will be added as soon as we have an clear spec addressing the comment in bug 171
