### ISSUE TITLE
Clarification needed for live trick mode?

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#172]
Comment in https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/52

"I think one should concentrate on making new VoD representations and just have them described in a new manifest (something like Manifest_trick.mpd)."

**Comment by TobbeEdgeware** [comment]
My thinking is that one should process all the test sequence segments and extract the IDR-frames into new smaller segments just containing IDR-frames and thus having a smaller size and add these as extra representations in a manifest. If one just extract the first frame in every segment, all segment numbering will work as usual in the simulator, so no change is needed to the code. This is similar to what I did for thumbnails which are available as a separate representation in the MPD http://vm2.dashif.org/livesim-dev/testpic_2s/Manifest_thumbs.mpd.

**Comment by waqarz** [comment]
@TobbeEdgeware this representation needs to be in a separate adaption set with trick mode signaling (http://dashif.org/guidelines/trickmode ) as documented in IOP guideline. The player needs to use this signaling to know this adaptation set is for trick mode. We cannot add this representation in the _same_ main adaptation set, else the DASH player can "automatically" and erroneously switch to this representation during normal playback; hence the need of a different adaptation set with the signaling.

**Comment by TobbeEdgeware** [comment]
@waqarz Sure, but it is just a matter of adding an extra adaptation set in a new MPD file. It will be transparently used by the simulator.

**Comment by haudiobe** [comment]
no actions necessary
