### ISSUE TITLE
SegmentTemplate format specifier

### ISSUE THREAD

**Issue by TheModMaker** [Dash-Industry-Forum/DASH-IF-IOP#177]
There has been some confusion within Shaka Player and some of our partners about how to handle `SegmentTemplate` substitution parameters.  DASH section 5.3.9.4.4 states the following:

>Each identifier may be suffixed, within the enclosing ‘$’ characters, with an additional format tag aligned with the printf format tag as defined in IEEE 1003.1-2008 [10] following this prototype:
> 
>  > %0[width]d

Since it mentions IEEE 1003.1, it suggests that it could be any general format specifier; but to me, the `following this prototype` after means that it must be the following format.  dash.js supports the more general form, supporting `d`, `x`, `i`, etc.; but Shaka Player only supports `d` since the text suggests that only that is valid.  So my question would be: is `$Number%05x$.mp4` a valid format?

The IOP guidelines offer no advice (that I can see); it would be helpful to include a clarification on this point.

**Comment by sandersaares** [comment]
There was a discussion internally in DASH-IF about this in March 2017. While it did not result in any addition to DASH or IOP, I paste here the explanation expressed in that discussion:

> The intention was to restrict to %0[width]d. 
> The reason was that the simple %0[width]d can be implemented w/o a library. If you need a full library for creating this, it may result in interoperability issues.

**Comment by sandersaares** [comment]
It was decided yesterday that the above clarification will go into IOP 4.2.

**Comment by joeyparrish** [comment]
Thanks!

**Comment by haudiobe** [comment]
addressed in v4.14
