### ISSUE TITLE
Forbid the use of variable-size components of xs:duration

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#181]
DASH uses the XML `xs:duration` data type in places, e.g. for `Period@start` and others. This data type allows one to express units that can only be resolved in relation to a real-time start timestamp - for example, a year and a month have different length depending on when you start counting. And minutes have leap seconds!

The XML datatype spec says this is fine. Obviously, this has serious interoperability implications, as nobody wants to (or even needs to) complicate DASH duration math with real-time references any more than absolutely necessary (only `MPD@availabilityStartTime`, I would say).

Ref: https://github.com/Dash-Industry-Forum/dash.js/issues/2511

I therefore propose the following addition to IOP:

-------------

MPD fields having datatype `xs:duration` shall not use the year and month units.

All units expressed in MPD fields of datatype `xs:duration` shall be treated as fixed size:

* 60S = 1M (minute)
* 60M = 1H
* 24H = 1D
* 30D = 1M (month)
* 12M = 1Y

**Comment by haudiobe** [comment]
Preference to only use seconds. And write it down how it works by reference to W3C spec

**Comment by haudiobe** [comment]
added to v4.2.1
