### ISSUE TITLE
Clarification on SegmentTemplate restriction for ISO BMFF Live Profile

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/DASH-IF-IOP#182]
At Hulu we have a collection of both VOD and LIVE assets and today the VOD assets are presented with **`SegmentBase`** and the LIVE assets are presented with **`SegmentTemplate`**. We are currently exploring the insertion of VOD based periods into a LIVE based stream that uses the ISO BMFF Live Profile, but the mixing of these two presentation types appears to be forbidden by the profile. We want to clarify if this was an intentional exclusion and if so what the reasoning behind it was.

Prior to v3.0 of the DASH-IF-IOP, the basic restriction on the presentation of segment information appeared to be that **`SegmentList`** should not be used, this being implied by the explicit disallowment at the **`Period`** level and ability to ignore at **`AdaptationSet`** and **`Representation`** level. ([DASH-AVC/264 v2.0](http://dashif.org/wp-content/uploads/2015/04/DASH-AVC-264-v2.00-hd-mca.pdf) 3.2.2):
> - The **`Period.SegmentList`** element shall not be present.
> - If the **`AdaptationSet.SegmentList`** is present in an **`AdaptationSet`** element then this **`AdaptationSet`** element may be ignored.
> - If the **`Representation.SegmentList`** is present in a **`Representation`** element then this **`Representation`** element may be ignored

With v3.0 of the IOP, the wording was changed in 3.2.2.2 such that **`SegmentTemplate`** must be present at some level in the Representation hierarchy to provide segment information ([DASH-IF-IOP v4.2](http://dashif.org/wp-content/uploads/2018/04/DASH-IF-IOP-v4.2-clean.pdf) 3.2.2.2):
> The Representations contain or inherit a **`SegmentTemplate`** with `$Number$` or `$Time$` Identifier.

This rewording is what makes us believe the ISO BMFF Live Profile is restricted to only **`SegmentTemplate`** presentation due to an additional restriction within the base ISO 23009-1:2014 5.3.9.1:
> At each level at most one of the three, **`SegmentBase`**, **`SegmentTemplate`** and **`SegmentList`** shall be present.

While it is possible to generate a **`SegmentTemplate`** representation for the VOD content, we would like to keep the **`SegmentBase`** representation as it is far more concise and would utilize the existing caching on our CDN edges.

Any thoughts would be appreciated!

**Comment by haudiobe** [comment]
We want to permit this, we need to make it clear.

**Comment by technogeek00** [comment]
@haudiobe following up in a statement from my meeting notes, there was the previous desire to explicitly prevent usage of `SegmentList`, in making this clearer do we just want to reword 3.2.2.2 to allow either `SegmentTemplate` or `SegmentBase`? Or should we remove all segment signaling restrictions?

**Comment by haudiobe** [comment]
Use the same wording as in MPEG and DVB. Content can be offered, but client may ignore.

**Comment by irajs** [comment]
The DASH Common profile allows the use of SegmentBase and Segmenttemplate, but each period should use only one of them. This provides the possibility of adding on-demand content to live content (that was one of the reasons for creating such profile).

In DASH-IF IOP, it says "DASH-IF Interoperability Points use ISO base media file format [7] based encapsulation and provide significant commonality with a superset of the ISO BMFF On-Demand, the ISO BMFF Live profile, and the ISO BMFF Common Profile as defined in ISO/IEC 23009-1" and 
"The MPD shall conform to the ISO Base Media File Format Common profile as defined on ISO/IEC 23009-1:2014/Amd.1:2015"

Therefore, DASH-IF IOP already supports the use case. Maybe we need to make it more clear.

**Comment by technogeek00** [comment]
@irajs I agree the high level scoping provided in 3.1 does allow usage of **`SegmentBase`** and **`SegmentTemplate`** within a single MPD and only one type per **`Period`**, but it seems like we still should still reword 3.2.2.2 to clarify there is no further restriction. Though based on discussions we only want to state **`SegmentBase`** and **`SegmentTemplate`** as **`SegmentList`** has other problems associated with its inclusion.

**Comment by technogeek00** [comment]
Addressed in v5 update
