### ISSUE TITLE
Phrasing of 6.4.5 regarding side-loaded segmented subtitles is unclear

### ISSUE THREAD

**Issue by chrisfillmore** [Dash-Industry-Forum/DASH-IF-IOP#184]
DASH-IOP v4.1, section 6.4.5, lines 19-20 state:

> If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments shall be used with timing according to [29].

It is not clear that *both* TTML and WebVTT segments need to be packaged in ISOBMFF. It could be interpreted to mean that only TTML needs to be packaged in ISOBMFF, but WebVTT could be plain text.

Based on these discussions:
https://github.com/google/shaka-player/issues/1405
https://github.com/google/ExoPlayer/issues/4132

...our interpretation is that the spec requires ISOBMFF for *both* TTML and WebVTT. As such, I believe this should be rephrased to something similar to:

> If segmented subtitles are needed, such as for live sources, segments shall be packaged in ISOBMFF containers, in TTML or WebVTT format, with timing according to [29].

**Comment by haudiobe** [comment]
added to v4.2.1
