### ISSUE TITLE
Clarification on AvailabilityTimeOffset attribute possible locations

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/DASH-IF-IOP#189]
ISO/IEC 23009-1:2014(E) introduced availabilityTimeOffset and availabilityTimeComplete attributes in the BaseURL tag. So far we have seen examples of use of these parameters in the top BaseURL tag of the MPD, like in the LiveSIM manifests (cf https://vm2.dashif.org/livesim-chunked/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd). Which means that all representations will share the same availabilityTimeOffset value.

On page 58, ISO/IEC 23009-1:2014(E) says "If the @availabilityTimeOffset attribute is present **for a Representation**, then the adjusted segment availability start time is determined by subtracting the value of @availabilityTimeOffset from the Segment availability start time."
But there is no such @availabilityTimeOffset attribute in the XML schema for Representation.
Was the intent rather to say : "If the @availabilityTimeOffset attribute is present **for a BaseURL of a Representation**, then the adjusted segment availability start time..." ?

In DASH-IF-IOP-v4.2 we suggest on 4.3.2.2.5 that a SegmentTemplate.SegmentTimeline can have a @availabilityTimeOffset attribute. Is it really the case per the MPEG spec ? If it's the case, why not allow the @availabilityTimeOffset attribute for a simple SegmentTemplate without nested SegmentTimeline ?

In 5.1.3.3.2 this is even wider : "In case of dynamic MPDs, Period-level BaseURL@availabilityTimeOffset allow earlier availability start times. A shorthand notation @availabilityTimeOffset="INF" at a Period-level BaseURL indicates that the segments within this period are available at least as long as the current MPD is valid. This is the case with stored ad content. **Note that DASH also allows specification of @availabilityTimeOffset at Adaptation Set and Representation level**. "
Which is partly reflected on the XML schema page 123 where we can see BaseURL availabilityTimeOffset="INF" nested inside an AdaptationSet tag.

So I'm wondering what is exactly our recommendation here. Do we mean that :
- If you want to apply the same availabilityTimeOffset value to all Representations, you place it in the top BaseURL tag
- if you want to apply different availabilityTimeOffset value to different Adaptation Sets, you add a BaseURL tag per Adaption Set with a different availabilityTimeOffset value
- if you want to apply different availabilityTimeOffset value to different Representations, you add a BaseURL tag per Representation with a different availabilityTimeOffset value

If multiple levels would be used, would one take precedence over the others or would we stack the ATO values across all the nested levels?

And how to interpret 4.3.2.2.5 ?

**Comment by haudiobe** [comment]
Use Cases:
- different offerings on different networks (On a BaseURL basis)
- mixing On-Demand/VoD with Live (On a Period basis)
- different offerings for specific encoding (on Adaptation Set/Representation)
- also for indicating non-complete offerings for chunked transfer (on all three levels)
We need to check the details of the MPEG specification first based on discussion. If MPEG Is unclear, we need to come to a proposal on our end and use this and inform MPEG. If MPEG is clear, we need to update our IOP doc to address this properly. If we have large inconsistencies, we may need new signalling.

**Comment by nicoweilelemental** [comment]
Example of MPD currently generated by FFmpeg : each representation gets a possibly different ATO value, carried by the SegmentTemplate tag.

`<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
	profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:dvb:dash:profile:dvb-dash:2014"
	type="dynamic"
	minimumUpdatePeriod="PT500S"
	suggestedPresentationDelay="PT4S"
	availabilityStartTime="2018-06-04T09:21:45Z"
	publishTime="2018-06-04T09:26:00Z"
	timeShiftBufferDepth="PT19.2S"
	minBufferTime="PT9.6S">
	<ProgramInformation>
	</ProgramInformation>
	<Period id="0" start="PT0.0S">
		<AdaptationSet id="0" contentType="video" segmentAlignment="true" bitstreamSwitching="true">
			<Representation id="0" mimeType="video/mp4" codecs="avc1.4d4028" bandwidth="832848" width="1920" height="1080" frameRate="25/1">
				<SegmentTemplate timescale="1000000" duration="2000000" availabilityTimeOffset="1.960" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1">
				</SegmentTemplate>
			</Representation>
			<Representation id="2" mimeType="video/mp4" codecs="avc1.42c00d" bandwidth="332048" width="320" height="170" frameRate="25/1">
				<SegmentTemplate timescale="1000000" duration="2000000" availabilityTimeOffset="1.960" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1">
				</SegmentTemplate>
			</Representation>
		</AdaptationSet>
		<AdaptationSet id="1" contentType="audio" segmentAlignment="true" bitstreamSwitching="true" lang="eng">
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="199675" audioSamplingRate="48000">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
				<SegmentTemplate timescale="1000000" duration="2000000" availabilityTimeOffset="1.979" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1">
				</SegmentTemplate>
			</Representation>
			<Representation id="3" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="91746" audioSamplingRate="22050">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
				<SegmentTemplate timescale="1000000" duration="2000000" availabilityTimeOffset="1.954" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1">
				</SegmentTemplate>
			</Representation>
		</AdaptationSet>
	</Period>
	<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-xsdate:2014" value="https://time.akamai.com/?iso"/>
</MPD>
`

**Comment by haudiobe** [comment]
Address in Cor.3 of ISO/IEC 23009-1 second edition as well as in v4.2.3 of IOP
