### ISSUE TITLE
Content Protection 

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/DASH-IF-IOP#194]
See [49](https://github.com/Dash-Industry-Forum/CPIX/issues/49) under CPIX repository. 
For this bug, using the ContentProtection element with the schemeIdUri=&quot;urn:mpeg dash:mp4protection:2011&quot; allows having this information. This is an acceptable solution but the IOP text is not really clear on the requirement of having it. It is accepted that it is mandatory but shall be clearly stated.

**Comment by haudiobe** [comment]
added to v4.2.2
