### ISSUE TITLE
Inconsistent spelling for schemeIdUri (again)

### ISSUE THREAD

**Issue by joeyparrish** [Dash-Industry-Forum/DASH-IF-IOP#196]
It seems that the same problem in #112 is back.  Quoting that issue, "The spelling for schemeIdUri is not consistent in DASH-IF-IOP document. There are three different variants: schemeIdUri, schemeIdURI, schemeIDURI."

The inconsistent case is back in v4.2 of the IOP, and it seems that it has never been corrected in the spec text, either. The 2014 spec and 2015 corrigenda both appear to be case-inconsistent as well.

Can we get both the IOP and the spec fixed?  Thanks!

**Comment by haudiobe** [comment]
added to v4.2.3
