### ISSUE TITLE
Could somebody explain about 'change lead time' with an example?

### ISSUE THREAD

**Issue by junsoopark** [Dash-Industry-Forum/DASH-IF-IOP#198]
Hi there,

I could see 'change lead time' in IOP document v4.2, but I'm being confused..
Could somebody explain about the statement below and 'Figure 10: Different properties of a segment stream'?

>  4.11.2.2. Service Considerations
...Such changes are typically anticipated only on short notice, i.e. within a few seconds. In the following we refer to the time that changes are announced as change lead time. The service should also provide a minimum change lead time, i.e. the smallest time in media time between the change being announced in the stream and the time between the change occurs. ...

Thank you in advance.

**Comment by haudiobe** [comment]
see v4.2.3
