### ISSUE TITLE
Clarification for DASHEventMessageBox id field

### ISSUE THREAD

**Issue by damienlevin** [Dash-Industry-Forum/DASH-IF-IOP#201]
Hi,

Could you provide some clarification on the meaning of the DASHEventMessageBox id field semantic ? From section 5.10.3.3.4:
> id: a field identifying this instance of the message. Messages with equivalent semantics shall have the same value, **i.e. processing of any one event message box with the same id is sufficient.** 

What is the scope of the highlighted sentence ?
For instance, what is the expected player behavior for reporting events when:

1. Within a single representation two esmgs with different timestamps but a same id are encountered.
2. Within two different representations (audio/video) two esmgs with a same timestamp and id are encountered.
3. Within two different periods two esmgs with a same id are encountered.

Thanks

**Comment by haudiobe** [comment]
we addressed the issue in [DCOR.3](http://files.groupspaces.com/dashif/files/2194173/ZkK0ST07OfhP69vkCUpo/w17860.zip) of DASH. Please find attached the document. Can you check if it serves the purpose.

**Comment by haudiobe** [comment]
further discussion on e-mail and moved to MPEG
