### ISSUE TITLE
DASH Multi-Period Help

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#211]
Nam at Imagine Communications (copied).

We have not been able to generate multi-period content that transitions smoothly in the player, often resulting in stalls of varying duration between periods.  We would like to validate our understanding and would appreciate any pointers.
 
Background:
We’re performing SSAI and observe a timing issue at the transition between periods.  We’re testing against the reference client, dash.js 2.9.1, and find in the console logs that reporting next Period has not started, and it continues to search for a next segment in the previous Period.  We’re seeing similar issues, though it appears much worse, in other clients such as Exoplayer and Shaka.
 
The source uses a single period with AST set to epoch, where s@t is the offset from AST to roughly the current time.  Period@start and PTO are set to 0.  We splice the Period at the segment where it lines up to the presentationTime indicated by the Event in the EventStream.
 
We’d like to verify our understanding of timing and requirements:
1.	Our general understanding of timing of segments:
Segment_Availability (wall clock) = AST + Period@start + (s@t – PTO)/timescale
2.	Period@start
a.	Should not change across manifest updates.
b.	Can be set to 0 for the first Period.
c.	Can be omitted for subsequent Periods, so long as Period@duration is set on previous Periods.
3.	Period@duration
a.	Can be omitted, if Period@start is explicitly set.  Which is preferred?
b.	Question if set – When there are multiple AdaptationSets, the duration of each AdaptationSet may not be equivalent.  What should the value of Period@duration be set here?  (ie the longest or shortest AdaptationSet, or one with role main?)
4.	presentationTimeOffset (PTO)
a.	Should not change across manifest updates
b.	If the original source does not contain a PTO, can or should this be set? 
c.	If we need to set it, is it correct to assume AdaptationSet with role main is used to derive PTO?
d.	If other AdaptationSets are in different timescales, the math to generate the equivalent PTO  from 4c. may not divide evenly and contain a fractional component, causing rounding errors.

**Comment by sandersaares** [comment]
Notes for discussion from my first pass at this:

* Proper handling of leap seconds may be important a presentation such as the one described (#161).
* Given the reference to `s@t` I assume we are dealing with `SegmentTemplate+SegmentTimeline` addressing.
* Point 3b is currently under discussion in IOP; my personal opinion is "the period determines what is presented, the representations provide the content for the period and must provide continuous content for the entire period from start to finish"
* I do not understand point 4b. PTO describes the relation of media sample timing to MPD timing. There is always a PTO; it may be that you do not know the right PTO value, in which case you need to find out (to decide which timestamp on the sample timeline matches period start).
* 4c does not seem right - PTO is not derived from anything, it is a decision made by the packager when it determines how to align the timelines.
* 4d depends on 4c, so is invalid via indirection.

**Comment by ojw28** [comment]
Notes for discussion:

* Point 1 - I don't think I understand what is being calculated, or why.
* Point 2 (a), (b) and (c) all look correct.
* Point 3 (a) - Roughly speaking, yes. I think the important property is that the manifest must contain sufficient information to allow the client to calculate `PeriodStart` for every period. The process for doing this is unambiguously defined in `ISO/IEC 23009-1:2014(E)` section `5.3.2.1`. I would expect clients to handle all three of the bullet points in that section (ignoring the final one about Early Access Periods).
* Point 4 - I agree with @sandersaares that the description seems confused about what PTO is.

I'd be happy to take a look at a test stream and suggest what's wrong with it. It's extremely difficult to tell from a description.

**Comment by sandersaares** [comment]
F2F notes:

* 3b was decided in favor of "no gaps" interpretation.
* 4 is probably a misunderstanding.
* Point out this thread to issue author and see if our comments clarify anything.

**Comment by sandersaares** [comment]
I think this all got sorted and the feedback was taken into account when formulating the interoperable timing model. Closing as no longer relevant.
