### ISSUE TITLE
Use CMAF terminology in v5

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#217]
I propose we start taking up usage of CMAF terminology in IOP v5, as it seems more understandable than the DASH terminology in several places (as would be expected from a newer spec).

Most critically in my view, the distinction between "HTTP-addressable entity" (segment) and "byte-range of HTTP-addressable entity" (subsegment) that we inherit from DASH causes a lot of cognitive overhead and difficulty understanding text. There is no need for that distinction in most cases.

The CMAF definition is a lot more sane:

> A CMAF segment is a CMAF addressable media object containing one or more consecutive CMAF
fragments from a CMAF track.

In other words "DASH segment" and "DASH subsegment" are both "CMAF segment". In case a distinction needs to be drawn, it can be done explicitly.

I therefore propose that we use "CMAF segment" which means "DASH (sub)segment". We can explicitly refer to "DASH segment" or "DASH subsegment" if we need to.

I also propose that we use CMAF terms elsewhere as appropriate (though it might be less critical for understandability there) and define a chapter to clarify any relationships that we feel need clarification.

We should feel free to break away from cumbersome DASH wording in this and also other regards, in the interest of understandability. There is a fair bit of needless linguistic complexity in DASH that we can work to eliminate.

**Edit**: According to definition of CMAF segment and CMAF addressable media object, I would call a "DASH subsegment" a "CMAF segment" because a DASH subsegment is an addressable media object in my view. But then CMAF text itself says that CMAF segment == DASH segment. As it stands, I consider the latter statement in CMAF an error.

**Comment by haudiobe** [comment]
I disagree a lot on what you say. DASH was done independent on the container format. You can use it with MPEG-2 TS and WebM and people do. 

And saying that CMAF is simpler is just the reason that CMAF does not have looked into corner-cases. I am ok to adapt CMAF as the Segment format once we have solved all compatibility issues, but be sure that CMAF is not the solution to the problems you are mentioning.

**Comment by sandersaares** [comment]
> DASH was done independent on the container format. You can use it with MPEG-2 TS and WebM and people do.

Sure. But I speak here only in the context of IOP, which is BMFF specific. I do not think we need to cover non-IOP usages when we make interoperability guidelines.

A related question is whether we need to consider BMFF scenarios that may deviate from CMAF. This I do not have an answer to.

> I am ok to adapt CMAF as the Segment format once we have solved all compatibility issues, but be sure that CMAF is not the solution to the problems you are mentioning.

I agree with both points you make. Adopting CMAF when we are ready for it sounds sensible. And it is certainly not the solution to the problems I mention - but it is a part of the solution. We also need to work to transform not only the language, not only the specs we reference but also the guidelines we write into optimally understandable forms.

**Comment by sandersaares** [comment]
This issue seems to be out of date with regard to ongoing discussions in v5 editing task force, so I close it here as anyone reading it would be misled by the content in its present form.
