### ISSUE TITLE
Require Period@duration *and* MPD@mediaPresentationDuration if fixed-duration MPD

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#219]
IOP currently says that either `Period@duration` of the last period or `MPD@mediaPresentationDuration` must be present. The implication being that the client looks up whichever is present and calculates the other accordingly.

This looks to me like needless complexity. All the information to calculate both of these values is going to be present in the MPD. There is no need here for client knowledge or involvement. Let the packager do the calculations so that both values are correct.

The service should bear the burden of such calculations, not the client - you create the MPD once but play it in many different players. We can expect better interoperability if we limit the needless complexity that must be re-implemented and re-interpreted in every client.

Thus I propose we require that both values are present if the last period has a fixed duration.

**Comment by haudiobe** [comment]
This is a postroll use case, where an xlink controls the duration of the last Period. It is also relevant for on-demand content where the duration of the xlink Period are determined by the ad decision system. Options are to define the last Period.

**Comment by sandersaares** [comment]
This is very painful. It basically makes MPD@mediaPresentationDuration unusable in the timing model, just an optional "maybe you have it maybe you don't" extra.

The use cases feel valid to me. I think we just need to adjust our timing model to not depend on this attribute.

**Comment by sandersaares** [comment]
I will attempt to adjust the timing principles in #210 not to rely on MPD@mediaPresentationDuration.

**Comment by sandersaares** [comment]
Adjusted #210 not to use MPD@mediaPresentationDuration.
