### ISSUE TITLE
[CPS] Are KID changes period-connected?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#238]
DASH has the concepts of period connectivity and continuity. I request that it be defined by IOP whether changing the `default_KID` is a change that breaks period connectivity. Possibly other DRM parameters also need to be considered here.

My suspicion is that KID chanbge is not period-connected because a KID change changes the initialization segment ("functionally equivalent init segments" being the criteria of connectivity) but I am not certain of this. At any rate, we might want to find out what we can do to maximally enable seamless transitions in case of KID changes in situations where seamless transitions would be possible if the content were in the clear.

**Comment by lpiron** [comment]
Can you clarify what scenario you have in mind?
Within an `Adaptation Set`, changing the `default_KID` indeed should be done at `Period` boundary as it means changing the initialization segment but `KID` can change during this `Period` (key rotation).
Looks like to try to precisely define what in content protection (encryption, key management, output control, device authentication....) can create a non-seamless transition.

**Comment by sandersaares** [comment]
The scenario is that of a key change introduced by a new period, exactly.

My main question is simply: is it OK to put the `period-connectivity` descriptor on such representations whose key changes? Should a packager do this? Can clients handle KID changes seamlessly?

But I agree with your paraphrasing, which is a much better way to view the subject (to define what is required for seamless key changes).

**Comment by sandersaares** [comment]
Related? https://github.com/Dash-Industry-Forum/dash.js/issues/2950

**Comment by sandersaares** [comment]
I think we discussed this and reached the conclusion that they are indeed not period connected. Anyway, I added a note saying so in the timing model, which I guess satisfies the immediate need and answers my question, so I close this.
