### ISSUE TITLE
Revisit Initialization range requirement for on-demand content

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/DASH-IF-IOP#242]
This is a request to revisit https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/154. Looking back at the minutes, it was decided that requiring initialization range for on-demand content might be tricky, and that "reading 1000 bytes is probably enough" wording was added to DASH IOP instead. I'd like to suggest again that initialization range should be required, because:

1. It seems highly preferable to require it. The current 1000 bytes fudge isn't a good solution.
1. In practice, the initialization range is pretty much always 0 up to the start of the `indexRange`. `indexRange` is already required by DASH IOP. To me, this suggests that it shouldn't be tricky at all to also require initialization range, although perhaps I'm missing some context.
1. I think the vast majority of existing content already includes initialization ranges. ExoPlayer has _never_ supported on-demand content where the initialization range is omitted, and I don't remember us ever having received a complaint by a content provider. The only content I've ever seen where it is omitted are some of DASH-IF's own test vectors.

**Comment by sandersaares** [comment]
IOP is OK and the relevant text is now in master branch, so I close the issue.
