### ISSUE TITLE
The range of segment references described in a dynamic MPD

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#247]
The clause: 

A dynamic MPD must remain valid for its entire validity duration after publishing. In other words, a dynamic MPD SHALL supply enough segment references to allow the time shift window to extend by the MPD validity duration defined by MPD@minimumUpdatePeriod.

is not clear. 

IMU:
1. MPD shall supply enough segment references to allow the time shift window.
2. The time shift window can be extended to include [MPD publish time, MPD publish time + MPD@minimumUpdatePeriod].

So suggest to change to:
A dynamic MPD must remain valid for its entire validity duration after publishing. In other words, a dynamic MPD SHALL supply enough segment references to allow the time shift window to be extended to MPD publish time + MPD@minimumUpdatePeriod.

**Comment by sandersaares** [comment]
Suggestion accepted.
