### ISSUE TITLE
number of sidx boxes in on-demand 

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#249]
In indexed addressing:

"The index segment SHALL consist of a single Segment Index Box (sidx) as defined by [ISOBMFF]. The field layout is as follows:"

Do we still want to limit the sidx box to one? if yes:
"The index segment SHALL include one and only one single Segment Index Box (sidx), the syntax of which is defined by [ISOBMFF]:"

**Comment by sandersaares** [comment]
Please clarify what you mean by this. The two statements above seem equivalent to me.

**Comment by sandersaares** [comment]
I see. Yes, it looks like we limit to 1 intentionally. I found this relevant quote in IOP:

> Note 2: The single sidx restriction was introduced in version 3 of this document
> based on deployment experience and to enable alignment with DVB DASH.

**Comment by irajs** [comment]
great. thanks for confirming it.
