### ISSUE TITLE
Example 6 segment nominal start time

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#251]
Shouldn't start at 8 sec or 12 sec and not 10?

**Comment by sandersaares** [comment]
I see what you mean: 10 is not divisible by 4, so if we have 4 second segments then does the example imply something special if our exsample segment starts at 10s?

In fact, there is nothing special here - the first segment does not need to start at 0s, so an arbitrary example segment may have any start time and still be valid.

However, the reader of the example should not need to think about this, as this is not really what the example is about. I will adjust the example to a start time divisible by 4.
