### ISSUE TITLE
MPD removal: Unclear sentence

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#255]
An MPD update removing content SHALL NOT leave EarliestRemovalPoint outside the time span of all periods unless this point is beyond the end of a fixed-duration MPD (MPD@availabilityStartTime + MPD@mediaPresentationDuration).

**Comment by sandersaares** [comment]
I will just delete this sentence - I think it just tries to (unsuccessfully) clarify implications of other statements.
