### ISSUE TITLE
Can I return an XLink element as the response to an XLink resolution?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#267]
Consider I have the folllowing:

```
<Period xlink:href="..." xlink=actuate="onDemand">
</Period>
```

On actuation, the resolver returns a similar XLink element:

```
<Period xlink:href="..." xlink=actuate="onDemand">
</Period>
```

Is this valid? What should client behavior be? Does it resolve also the 2nd layer of xlink?

Alternative formulation of XLink response might also contain some playable period (but still with xlink attributes):

```
<Period xlink:href="..." xlink=actuate="onDemand" duration="PT54319S">
    <AdaptationSet>...</AdaptationSet>
</Period>
```

I am unable to find clear statement in IOP on what clients are expected to do and whether services may produce such content (and if so, why/when/how).

**Comment by haudiobe** [comment]
IOP 02/05/29: DASH Specification has language around this. Do we need to say more? Check 5.5.3!

**Comment by technogeek00** [comment]
For reference, paragraph in question:

> The remote element entity may contain another @xlink:href attribute with @xlink:actuate set
to onRequest. In this case the resolution to the referenced remote element entity is expected to
happen only when the latter is needed again after processing the content in the returned document.

**Comment by sandersaares** [comment]
Text in DASH 3rd ed looks clear enough. Thanks for clarifying!
