### ISSUE TITLE
Usage of Github Labels / Milestones

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/DASH-IF-IOP#299]
Following up from our weekly sync, we want to finalize the usage of labels as a process improvement for the general intake and management of issues in Github.

### [Label Overview](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/labels)
The following table describes labels created in the IOP repository for usage on issues

| Label | Description |
|---------|-----------------|
| bug | Issue describes a bug within the IOP |
| discussion needed | Issue needs general input from IOP members to move forward |
| duplicate | Issue was previously addressed |
| editorial | Issue is related to editorial changes |
| enhancement | Issue proposes an enhancement for the IOP |
| move to tf | A specific taskforce should address this issue |
| question | Issue is a question around DASH or IOP information that needs an answer |
| resolved | Issue has solution identified, but it needs implementation |
| wontfix | Issue is reviewed, but will not be addressed |

### Issue Process

1. Issues are submitted to the DASH-IF-IOP Github repository, anyone can submit issues but they remain without labels at first
2. During weekly IOP meetings
   - Look at issues without labels
      - Labels appropriate to issue are applied
      - Multiple labels may be applied to an issue, i.e. "bug" + "discussion needed"
      - Volunteers to follow-up can be directly assigned as owners
      - "duplicate" and "wontfix" labeled issues should be closed directly with a comment explaining the label
   - Follow up on issues based on labels/assignment
      - Assigned issues where people have progress to detail can be surfaced
      - Look at issues needing discussion and have discussion if time permits
      - Assign additional owners to move issues along
3. Owner of issue should progress it and adjust labels as necessary
   - When discussion is complete or solution detailed, mark with "resolved"
   - Issue is closed when no further action is necessary
   - If issue requires implementation, it is closed when associated PR closes

### [Milestones](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/milestones)
These are "goal posts" that can be used to group issues for easy progress overview. We want to have a minimal number of these at a time and should relate to big initiatives.

**Comment by sandersaares** [comment]
> "duplicate" and "wontfix" labeled issues should be closed directly with a comment explaining the label

Do we even need the label? These labels would just categorize closed issues so seem low value.

I would also advocate against adding labels just to distinguish classes of issues if the workflow is the same (e.g. bug or enhancement - doesn't really matter if we handle them the same way). Sticking to only the working-process-relevant labels allows us to avoid some cognitive overhead.

I would look favorably upon labeling issues even outside the weekly calls. The labels to assign are usually obvious IMO and the calls are a very precious resource, so if whoever does the labeling can already do it before a call, we can make better use of our contributors during the call. That is, we should not set an expectation that labeling occurs exclusively in calls - that would ideally be only for non-obvious situations.

**Comment by haudiobe** [comment]
(IOP 05/07/19) 

- TF bugs would close it or bring in resolution
- Please add final comments until COB today

Zach takes into account the final comments from Sander and we take the proposal as a working process.
Thomas adds it to working processes.

**Comment by irajs** [comment]
I agree with Sanders to simplify the labels and process:

1. 4 labels as he suggested, with "editorial" meaning that an editorial fix that the editors  or any contributor can fix of it without discussion, and technical change to spec.
2. Process:
       a. Anybody can assign labels anytime (during submission or when reads the issue).
       b. TF looks at issues with this order:
                     - "move to tf" 
                     - "discussion needed"
                     - no label (if has time).
       c. If anyone doesn't agree with issues labeled  "editorial" or "resolved", they can write a comment and change the label to "discussion needed" and/or "move to tf"

**Comment by technogeek00** [comment]
Based on feedback and processes agree we should simplify, therefore we'll proceed with the suggested 4 labels and simplified process:

### [Label Overview](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/labels)
The following table describes labels created in the IOP repository for usage on issues

| Label | Description |
|---------|-----------------|
| discussion needed | Issue needs general input from IOP members to move forward |
| editorial | Issue is related to editorial change that can be directly implemented |
| move to tf | A specific taskforce should address this issue |
| resolved | Issue has solution identified, but it needs implementation |

### Issue Process

1. Issues are submitted to the DASH-IF-IOP Github repository, anyone can submit issues, IOP members can add appropriate labels.
2. During weekly IOP meetings
   - Look at issues without labels or owners
      - Discussion had if possible, otherwise "discussion needed" added
      - Mark editorial changes with "editorial" label if not already done
      - Volunteers to follow-up can be directly assigned as owners
   - Follow up on issues with `discussion needed` or where owners have updates
      - Issues with solutions identified marked with "resolved"
3. Taskforce Review
   - Each TF looks at issues with "move to tf" label
      - If TF has repository, creates appropriate issue in task force repository, closes IOP issue
      - If TF doesn't have repository, add comments around TF progress, keep issue open
4. Issue closure
   - Issues with no changes or that have been addressed outside of the main IOP document can be directly closed with a comment about the closure
   - PRs opened with changes appropriate to issue should reference issue by issue number
   - When PR is closed, issue should be closed with PR closure

### [Milestones](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/milestones)
These are "goal posts" that can be used to group issues for easy progress overview. We want to have a minimal number of these at a time and should relate to big initiatives.

**Comment by sandersaares** [comment]
>If TF has repository, creates appropriate issue in task force repository, closes IOP issue

There's a "move" function.

**Comment by haudiobe** [comment]
(IOP 19/05/14) Apply this and add it to working procedures. Final decision at f2f

**Comment by sandersaares** [comment]
> One additional suggestion to have a label that marks it resolved pending final comment until next IOP meeting

My suggestion is to just leave this type of issue unlabeled. If there is no label or owner, it means IOP needs to look at it. Adding this label would still mean the IOP needs to look at it, so makes no difference.

**Comment by haudiobe** [comment]
It makes a difference, because it automatically gets resolved if there is no comment.

 

Thomas

**Comment by irajs** [comment]
I'm ok with process but I agree with Thomas that we need to differentiate between no labels with solved-if-no-more-comment.

Also, based on the above process, it seems that open issues has to be discussed first in IOP call before moving to TF. In practice, a TF call might be earlier than the first IOP call allocating the open issue. I suggest the TF can add its comment to the issue by adding (discussed in TF, the resolution is:...), but without labeling, so that the next IOP call can close it. So basically TFs can look at open issues before they are marked as "move-to-tf".

**Comment by technogeek00** [comment]
Closing this out as result of F2F finalizing the work here.
