### ISSUE TITLE
What constraints does CMAF apply to sample timelines?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#301]
CMAF (2nd ed) section 6.3 "Late binding CMAF track synchronization" has a lot of statements about timelines but the chapter is extremely confusing to me and I fail to extract any meaning from it.

Right now, DASH works perfectly fine with the timelines of different adaptation sets completely independent. I can start one at value 1234, with timescale 56 and PTO 78 and another adaptation set can start at value 9876, with timescale 54 and PTO of 321.

Does 6.3 in CMAF constrain some of this? It is not obivous to me what impact the CMAF text has. What constraints do we need to align with here? Why does 6.3 in CMAF exist and what is it even trying to say?

I can see two possible interpretations:

1. Section 6.3 says that we need some numeric alignment between tracks (though unclear what it is).
1. Section 6.3 is just a roundabout way of saying "tracks need to be synchronized".

Is it one of these? Or something else entirely? I request expert assistance to understand what impact this has on DASH and IOP guidelines.

I think that one of the constraints is that the point where timestamp 0 exists is the same for all tracks. This constraint does not currently exist in DASH or IOP and is unexpected to me. What is the reason for this, if true?

But then again in 6.6.8 there are statements like "The CMAF track presentation time at CMAF presentation time zero is its “presentation time offset”, " which make me doubt that interpretation... how many presentation times are there?

**Comment by haudiobe** [comment]
Sander, I share your confusion on this. At this stage we believe that Clause 6 in the CMAF specification is more harming than useful and the editors consider to completely remove or at least simplify this. The core issue is documented in clause 7. I would refer more to the document provided here: https://1drv.ms/w/s!AiNJEPgowJnWgddMtq2mTiu2bmDDOA as a starting point. Let's improve this description for the mapping of CMAF to DASH.

**Comment by sandersaares** [comment]
I think my questions are addessed by the CMAF profile for DASH, so I close this now.
