### ISSUE TITLE
Get rid of the Gitreports spam generator

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#326]
It looks like this repo is getting a lot of spam entries via the Gitreports submission form. Every time I open my notifications there is new spam from this repo. I think we can safely get rid of that form - people can just submit via GitHub, which prevents spam.

**Comment by haudiobe** [comment]
I de-activated for now. We need to check if gitreports can fix the spam problem. Once done, we will check if we reopen github.
https://github.com/schneidmaster/gitreports.com/issues/146
