### ISSUE TITLE
Replace "move to tf" with specific TF label

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#339]
Right now if I want to find CPS task force assigned issues, there is really no good way to do it. "Move to tf" label is applied but does not say which TF.

I propose instead we use taskforce-specific labels such as "Ad insertion TF" "Ingest TF" and "Content Protection & Security TF".

**Comment by technogeek00** [comment]
Agreed this makes intention more explicit

**Comment by irajs** [comment]
(IOP Call 6/25) Agreed to have explicit label for each TF.

**Comment by technogeek00** [comment]
Labels created for active task forces
