### ISSUE TITLE
Context to other DASH aspects

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#349]
Provide the context to other DASH specification following 2.1 from IOP v4.3

Dynamic Adaptive Streaming over HTTP (DASH) is initially defined in the first edition of ISO/IEC 23009-1 which was published in April 2012 and some corrections were done in 2013 [1]. In May 2014, ISO/IEC published the second version of ISO/IEC 23009-1 [4] that includes additional features and provide additional clarifications. The initial two versions of this document where based on the first edition of ISO/IEC 23009-1. 

Version 4.3 was mostly relying on the on the amendments to the second edition, which where finally rolled into the third edition of ISO/IEC 23009-1 [reference] in 2019. 

This version of the document relies on the 4th edition of ISO/IEC 23009-1 that was technically frozen in July 2019 and is expected to be published by the end of 2019 as ISO/IEC 23009-1:2020.

This document was generated in close coordination with DVB-DASH [42]. The tools and features are aligned to the extent considered reasonable. In addition, DASH-IF worked closely with ATSC to develop a DASH profile for ATSC3.0 for broadcast distribution [reference].

**Comment by irajs** [comment]
Added most of above to #DASH and related standard. 

Also added a paragraph of CMAF.

Also created a section of the relationship of this version with previous versions.

**Comment by sandersaares** [comment]
I have iterated upon the above to focus on the important connections to other DASH aspects while minimizing verbosity. This should meet both the goals of being informative and of being succinct.

I close the issue as it was already addressed in August and then further iterated upon.
