### ISSUE TITLE
Comments on 7.1 Periods

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#359]
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#timing-period

An MPD SHALL define an ordered list of one or more consecutive periods. A period is both a time span on the MPD timeline and a definition of the data to be presented during this time span. period timing is relative to the zero point of the MPD timeline.

_this is not a requirement, but a definition._

Periods are self-contained - a service SHALL NOT require a client to know the contents of another period in order to correctly present a period. Knowledge of the contents of different periods MAY be used by a client to achieve seamless period transitions, especially when working with [[#timing-connectivity|period-connected representations]].

_Again this is not a requirement, but a statement of fact_

In a static MPD, the first period SHALL start at the zero point of the MPD timeline. In a dynamic MPD, the first period SHALL start at or after the zero point of the MPD timeline.

_unclear what this means. What is the "zero" point?_

In a static MPD, the last period SHALL have a Period@duration. 

_this is not a requirement from MPEG-DASH. mediaPresentationDuration is also good enough_

In a dynamic MPD, the last period MAY have a Period@duration, in which case it has a fixed duration. If without Period@duration, the last period in a dynamic MPD has an unlimited duration.

_unlimited is not clear_

**Comment by irajs** [comment]
Addressed all the comment along with Dash-Industry-Forum/Guidelines-TimingModel#10

**Comment by sandersaares** [comment]
As this has been addressed in August, I close the issue as it seems taken care of and was also discussed in some calls. If more comments arise, they can be processed separately.
