### ISSUE TITLE
DASH and related standards

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#361]
Change
DASH is an adaptive media delivery technology defined in [MPEGDASH]
to
DASH is a set of manifest and media formats for adaptive media delivery defined by [MPEGDASH]

**Comment by haudiobe** [comment]
How does this relate to #349 and #350?

**Comment by irajs** [comment]
Addressed and combined with #349

**Comment by sandersaares** [comment]
Closing as it was addressed in August.
