### ISSUE TITLE
Alignment with  DVB

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#363]
"This document was generated in close coordination with [DVB-DASH]. The features are aligned to the extent considered reasonable. To support implementers, this document attempts to highlight differences between [IOP] and [DVB-DASH]."

Is this true? It was true for IOP V3.0. Does the document still highlights the differences between two spec, specially with new additions to DVB?

**Comment by irajs** [comment]
addressed as the following:

This document was generated in close coordination with [[DVB-DASH]]. The features are aligned to the extent considered reasonable. The tools and features are aligned to the extent considered reasonable. In addition, DASH-IF worked closely with ATSC to develop a DASH profile for ATSC3.0 for broadcast distribution [[!ATSC3.0].

**Comment by sandersaares** [comment]
Closing as it was already addressed in August.
