### ISSUE TITLE
This document vs IOP

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#364]
1. the term "IOP" needs a clarification. Add the following to  section "Purpose" or "Interpretation", right before the last paragraph:

The document describing DASH-IF guidelines for interoperable implementation of streaming services and clients is known as "DASH-IF Interoperability Points Guidelines Document" or in brief "DASH-IF IOP". Each DASH-IF IOP is published with a version number. Each version outlines the changes from previous version.   In this document, the current version is referred to as "this IOP".

2. Replace "This document" with "This IOP" everywhere.

**Comment by irajs** [comment]
Addressed

**Comment by sandersaares** [comment]
I will close this since it was already addressed in August.
