### ISSUE TITLE
5.1. CMAF and ISO BMFF

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#367]
This section can be removed.

The SHALL statement should be moved to Media Segment section, under CMAF compatibility.

That section can start with:
Media Segments SHALL be compliant to [MPEGCMAF]  clauses 7-11.

Consequently:
(all the other current SHALL statements goes here as statement of fact).

**Comment by haudiobe** [comment]
I agree in principle, but we need to be very clear what we mean by "Media Segments SHALL be compliant to [MPEGCMAF] clauses 7-11"? It is not correct. We need to be clear where the interop point is. We had been very clear and careful in the ad insertion context. I propose we align with ad insertion doc.

**Comment by haudiobe** [comment]
(v5 editing: 08/07/2019) Suggestion to reference DASH Profile for CMAF.

**Comment by irajs** [comment]
Implemented as: 

## CMAF and ISO BMFF Requirements## {#cmaf-bmff-constraints}

Media segments SHALL be compliant to [[MPEGDASHCMAFPROFILE]].

Note: [[MPEGDASHCMAFPROFILE]] defines the media segment format using [[!MPEGCMAF]], which is largely based on [[!ISOBMFF]].

**Comment by sandersaares** [comment]
Closing as this has been addressed in August.
