### ISSUE TITLE
5.2.1. Periods

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#369]
Periods are self-contained - a service SHALL NOT require a client to know the contents of another period in order to correctly present a period. Knowledge of the contents of different periods MAY be used by a client to achieve seamless period transitions, especially when working with period-connected representations.
TO:
Periods are self-contained -  a client doesn't need to know the contents of another period in order to correctly present  the content in this a period (however, the timing of one period may rely of the order of periods). Knowledge of the contents of different periods may be used by a client to achieve seamless period transitions, especially when working with period-connected representations [reference to see period connectivity  signaling section].

Replace the rest of section with:

[MPEGDASH] clause 5.3.2  defines the period requirement in MPD authoring. Among others it requires the followings:

- All periods must be consecutive and non-overlapping. A period may have a duration of zero.

- In a static MPD, the first period must start at the anchor point of the MPD timeline. In a dynamic MPD, the first period must start at or after the anchor point of the MPD timeline.

- In a static MPD, the last period must have a Period@duration. In a dynamic MPD, the last period may have a Period@duration, in which case it has a fixed duration. If without Period@duration, the last period in a dynamic MPD has an unlimited duration.

Note: In a dynamic MPD, a period with an unlimited duration may be converted to fixed-duration by an MPD update. Periods in a dynamic MPD can also be shortened or removed entirely under certain conditions. See § 5.2.7.5 MPD updates.

- MPD@mediaPresentationDuration may be present. If present, it must accurately match the duration between the MPD timeline anchor and the end of the last period.  

This document additionally requires:
Clients SHALL calculate the total duration of a static MPD by adding up the durations of each period and SHALL NOT rely on the presence of MPD@mediaPresentationDuration.

Note: This calculation is necessary because the durations of XLink periods can only be known after the XLink is resolved. Therefore, it is impossible to always determine the total MPD duration on the service side as only the client is guaranteed to have access to all the required knowledge.

**Comment by haudiobe** [comment]
unlimited is not correct - it is unknown and it extends at least to NOW+@minimumUpdatePeriod with NOW the time when the MPD was available on the server. The duration is not yet know at the time NOW and may continue indefinitely. Please check 5.4.1

**Comment by irajs** [comment]
Combined above comments and revised the text accordingly.

**Comment by sandersaares** [comment]
I have further iterated on Iraj's adjustments as part of post-communityreview work.

The usage of "unlimited" I consider correct (or more correct than "unknown") but I have amended the text to better outline the concerns pointed out by Thomas.

I will close this issue since the original post has been integrated into the text already in August. Any additional comments can be handled separately.
