### ISSUE TITLE
use of "this document requires"

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#382]
[V5 Editing call 8/14] The phrase "this document requires" sometimes comes before a SHOULD or MAY. 

We need to improve the language to avoid confusion between "requires" and a optional/recommendation statement.

**Comment by irajs** [comment]
This is revised  in the intro section:

This document uses statements of fact (e.g. "is", "can", "must" and "may") when describing normative requirements defined in referenced specifications such as [[!MPEGDASH]] and [[!MPEGCMAF]]. [[RFC2119!]] statements (e.g. "SHALL", "SHOULD" and "MAY") are used when this document defines a new requirement or further constrains a requirement from a referenced document. In order to clearly separate the requirements of referenced specifications vs. the additional requirements set by this document, the normative statements in each section of this documents are separated into two different groups, ones starting with "(referenced specification) requires/recommends:" and the other ones starting with "This document requires/recommends:". See also [[#conformance]].

**Comment by sandersaares** [comment]
I believe this was already implemented by Iraj and is being further iterated upon by me during post-communityreview editing. Closing the issue as I consider it taken care of.
