### ISSUE TITLE
Guidelines reference non-existent part of 23009-1?

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/DASH-IF-IOP#383]
DASH-IF 4.3, section 3.9.2, Table 4, defines a `Label` node, which is documented with:

> See ISO/IEC 23009-1 [4], clause 5.3.7.2 Table 9.

ISO/IEC 23009-1 [4], clause 5.3.7.2 Table 9 doesn't say anything about a `Label` node. 23009-1 doesn't appear to define a `Label` node anywhere at all.

It's also documented as providing:

> a textual description of the content

but [this sample](https://dash.akamaized.net/dash264/TestCasesIOP41/MultiTrack/alternative_content/6/manifest_alternative_lang.mpd), which is from DASH-IF according to [this issue](https://github.com/google/ExoPlayer/issues/6297), doesn't appear to do this.

As far as I can see the `Label` node isn't clearly defined anywhere (e.g. it's somewhat unclear whether labels are supposed to look like `<Label>text</Label>` or `<Label @value="text"/>`).

**Comment by haudiobe** [comment]
(IOP 19/09/27): It should be <Label>text</Label>, but we check this with the MPEG spec.

**Comment by sandersaares** [comment]
`<Label>` is new in DASH 3rd edition (2019).

**Comment by sandersaares** [comment]
I think this can be closed - all is well with this in 4th edition.
