### ISSUE TITLE
Multiple protection schemes in one DASH period - possible conflict with CMAF?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#388]
This was discussed in IOP call but I think we do not have GitHub issue for it, so I file one.

Situation:

* CMAF states that one CMAF presentation shall be either `cbcs` or `cenc` encrypted but cannot contain both protection schemes together.
* DASH-IF wants DASH presentations to offer `cbcs` and `cenc` as alternatives in the same DASH presentation, for the client to choose from depending on client capabilities.

Do these two items conflict or not? It is ambiguous.

One interpretation is that one CMAF presentation is one DASH period, in which case we have a conflict. This conflict should be resolved (preferably by amending CMAF).

Another interpretation is that multiple CMAF presentations can be in one DASH period (as alternatives), in which case there is no conflict but the exact mapping here is quite unclear. This should be resolved by amending CMAF profile for DASH.

**Comment by sandersaares** [comment]
Response from MPEG:

> Regarding the use of CMAF presentation profiles with different encryption modes, we believe the use of CMAF Switching Sets with different encryption modes as different Adaptation Sets in a single DASH Period is allowed by the DASH specification. We included this use-case in the draft text of DAM1.

This sounds good and enables flexible behavior. I believe it still needs to be addressed in the CMAF profile for DASH.

I will create a PR for the security guidelines to resolve this from IOP guidelines point of view.

**Comment by lpiron** [comment]
Pull Request merged
