### ISSUE TITLE
@availabilityTimeOffset unit not mentionned

### ISSUE THREAD

**Issue by AChoteau** [Dash-Industry-Forum/DASH-IF-IOP#397]
This is a question regarding the @availabilityTimeOffset unit. The others time related attributes have their unit specified in the document, but I can't seem to find the unit for this one. 
Are there any rules regrading this?

**Comment by sandersaares** [comment]
![image](https://user-images.githubusercontent.com/9914262/84236733-cfa0e800-ab00-11ea-98cb-b56fc17ae3bf.png)

**Comment by AChoteau** [comment]
Thank you for the answer
