### ISSUE TITLE
$Number$ attribute calculate

### ISSUE THREAD

**Issue by junmediatek** [Dash-Industry-Forum/DASH-IF-IOP#403]
Hi
When we study mpeg dash spec, we meet a problem as below:
Mpeg dash fourth spec as below
If the Representation contains or inherits a SegmentTemplate element with $Number$ then the URL of the Media Segment at position k in the Representation is determined by replacing the $Number$ identifier by (k−1) + (kstart−1) with kstart the value of the @startNumber attribute, if present, or 1 otherwise.

Mpeg dash second spec as below
If the Representation contains or inherits a SegmentTemplate element with $Number$ then the URL of the Media Segment at position k in the Representation is determined by replacing the $Number$ identifier by (k-1) + @startNumber.

So, which one is right for $Number$?

**Comment by haudiobe** [comment]
It is always the latest specification, to the 4th edition is what matters. Please deprecate the 2nd edition. It was a bug fix.
