### ISSUE TITLE
It seems, that thumbnails adaptationset feature not working

### ISSUE THREAD

**Issue by alex-rsk** [Dash-Industry-Forum/DASH-IF-IOP#434]
I have tested https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_multiple_tiled_thumbnails.mpd, and haven't seen any thumbnail or some still image.

Checked in two browsers:
 * Brave Browser 131.1.73.89 
 * Chrome 131.0.6778.69
 
 OS Ubuntu Linux, x86_64
 
Is this feature removed or, sort of, glitchy?

**Comment by dsilhavy** [comment]
This works with dash.js: https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

If you hover over the progressbar you see the thumbnails:
<img width="1632" alt="Bildschirmfoto 2024-11-29 um 15 39 14 (2)" src="https://github.com/user-attachments/assets/2d786609-89aa-4cc7-9631-7fc3bd5609a7">

**Comment by alex-rsk** [comment]
Thank you and sorry for writing an issue.

I just thought it something like watermarks, an image which is visible during playback.
