### ISSUE TITLE
audio values to record in the MPD for HE-AAC v1

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#50]
From: Richard Bushell, Living.TV [mailto:rb@living.tv] 
Sent: Tuesday, April 28, 2015 12:26 PM
To: 'DASH-IF Administration'
Subject: DASH IOP3 clarification

Regarding DASH IOP3
----------------------------------

Can we seek clarification on what audio values to record in the MPD for HE-AAC v1 (i.e. SBR).
We have audio with SBR with an Audio Sampling Rate of 48000.
As I understand it, that means the underlying AAC has a Sample Rate of 24000, and the SBR has a Sample Rate of 48000.
In the MPD text file, should we record:
codecs="mp4a.40.5" audioSamplingRate="24000" timescale="24000"
or:
codecs="mp4a.40.5" audioSamplingRate="48000" timescale="48000"
The DASH IOP3 spec does not clarify the correct way of representing this in the MPD.
Please advise asap, or provide an email for forwarding this on to the correct person or team for clarification of this issue.
p.s. It might also we worth clarifying HE-AAC v2 (i.e. PS) at the same time.

Thanks.

Richard

**Comment by arjen4157** [comment]
In DVB BlueBook A168 it reads ' Specifies the output sampling rate of the codec in units of Hz, e.g.  “
48000”  for  48  kHz' . So for SBR and SBR+PS it is double the rate of the underlying AAC.

**Comment by haudiobe** [comment]
> Hi Richard,
> 
> if you don't want to create a second set of representations in AAC-LC, you you can re-use your mp4 files. All you need is a second adaptation set (< 10 lines of xml) in your MPD referencing the same representations.
> 
> If this is not an option, you should provide codecs=mp4a.40.5 and a sample rate of 48 kHz. 
> 
> The values in the MPD are usually only a hint to the access engine. What client implementation are you using?
> 
> Best regards,
> Ingo 
>
