### ISSUE TITLE
Update to Timing Model in section 3.2.7

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#54]
It would be good to explain the three timelines in use and which timelines each attribute is measuring or setting.  
1.	UTC timeline.  @AST is a UTC time that coincides with the instant each live media sample begins to encode.  Live Segments become available after all their samples have been encoded and packaged.  @AST is the anchor point for all 3 timelines, and is expressed as a UTC time (in Zulu Time?).  
2.	The presentation timeline is defined to be zero at @AST, is measured in MPD@timescale, and increases continuously for the duration of an MPD at the rate of UTC (ignoring leap seconds).  The Presentation time at the start of a Period is the sum of all prior Period durations, the duration of each Period determined by Period@start presentation time of the next Period, or the Period@duration of the Period.  Period start and duration is measured in MPD@timescale.  
3.	The media timelines are the sample presentation times encoded in ISO Media track fragments (‘tfdt’ baseMediaDecodeTime, sample durations, and composition offsets).  

The media timeline origin for tracks in ISO Media files is defined to be zero. AdaptationSet@presentationTimeOffset defaults to zero, which is normally the case for complete files sequenced as Periods.  DASH abstracts media time to allow Representations that are portions of tracks with arbitrary origins in the past, such as UTC 1/1/1970.  For partial files or live streams, AdaptationSet@presentationTimeOffset indicates the media composition/presentation time of the samples that should be synchronized to the Period@start.   

Explaining the diagram
Each Period must include Period@start* (except for an optional “early availability Period” at the start of MPD?).  Period@start starts presentation of a Period at the elapsed presentation time since @availabilityStartTime, measured in MPD @timescale.  

The value of Period@start for an ad can be chosen to coincide with an insertion point in the live stream by setting Period@start to a presentation time duration equal to the UTC time difference between @availabilityStartTime and the scheduled encoding time of the insertion point in the live stream.  

@presentationTimeOffset in the ad Period will normally default to zero assuming the prerecorded ad is a complete file starting from baseMediaDecodeTime of zero.  @presentationTimeOffset for the live stream will usually not be zero because the encoders are usually started prior to presentation availability, so the media timestamps on the first available Segments will have increased since the encoders started.  Encoding timestamps may be set to UTC (as though the encoder was turned on 1/1/1970 at midnight).  The @presentationTimeOffset for each Adaptation Set is the media time at the start of the Period.  Live Periods will have the same @presentationTimeOffset as long as the media is continuously encoded, because UTC time and media time increase at the same rate and maintain the same offset. 

*(I think we should clarify the Period values for the next live program Period that follows the ad Period(s).  Its @start should be the exact duration of the prior Period added to the prior Period@start.  Since the ad Period duration isn’t known in advance (decided by the ad server), maybe the downloaded Period should include Period@duration to determine the start of the next ad or program Period, rather than the MPD generator needing to know the ad response of each client to set a different Period@start for resuming the program?  The other question is the correct value for @presentationTimeOffset of the resume Period.  If it copies the original @PTO of the first live Period, then it will remain on the live edge, and replace 1 minute of live content with 1 minute of ad content rather than falling behind the live edge by 1 minute.  

I think there’s a functional gap in the MPD timing model compared to e.g. SMIL.  It would be nice to say a live Period starts “onEnd” of the prior ad Period without having to know the exact ad duration and setting the Period@start for the next live Period in advance.  The player has to do live edge availability synchronization whenever the last ad period in a pod ends.  The problem is partly due to one server generating the program MPD and an ad server later generating ad Periods with durations the MPD server doesn’t know in advance, and potentially different for each client with targeted ads.  Note:  if you just combine a simple linear live presentation with SCTE-35 messages that overlay ads through a second element; all the difficulties go away.)  

A before and after XLink MPD example corresponding to the diagram would be the best documentation.  Just pseudo code or a table with a few attributes like @AST, @PTO, @start, @duration.

**Comment by waqarz** [comment]
"Live Segments become available after all their samples have been encoded and packaged" to me causes confusion with spec statement "Segment availability start time of a Media Segment is the sum of .... the MPD duration of the Media Segment". Considering the spec defines that the "MPD duration may be approximate", a segment with larger duration than average has to be made available earlier than their actual duration dictates. An alternate statement could be: Live Segments become available after their documented MPD duration has elapsed since their respective MPD start time, (or some thing in this effect)

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf
