### ISSUE TITLE
SCTE 214 references

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/DASH-IF-IOP#60]
Several places in v3.1 mention SCTE DVS 1202 and SCTE DVS 1208 documents.
These were references for the pre-publication documents, and should be replaced to the publicly available standards, as follows:
     SCTE DVS 1202 => ANSI/SCTE 214-1
     SCTE DVS 1208 => ANSI/SCTE 214-3

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf
