### ISSUE TITLE
Clarification on codecs

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#64]
We have provided codec strings, perhaps should provide some relaxation. e.g. for HEVC all the codec strings set general_non_packed_constraint_flag (X.X.X.X.B0), while encoded streams have this cleared (X.X.X.X.90). This is non crucial for HEVC as the spec says: "Decoders may ignore the value of  general_non_packed_constraint_flag, as there are no decoding process requirements associated with the presence or interpretation of frame packing arrangement SEI messages or segmented rectangular frame packing arrangement SEI messages."

**Comment by waqarz** [comment]
Clarification needed on codec strings:
- By providing a list of codecs, are we just providing some examples or restricting inter-operable content to these set of selected codecs?
- If latter (i.e. we want to restrict inter-operable content to these set of selected codecs), shouldn't at least the level be an upper limit only e.g. by allowing any codec *up to* level 4.1, instead of restricting to level 4.1; a lower resolution video could use a smaller level then.
- If this is not clear in IOP document, then we should add this clarification: agreement needed.

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf
