### ISSUE TITLE
DASH-IF URNs

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/DASH-IF-IOP#65]
Section 5 uses "urn:org:dashif:asset-id:2014" to identify an asset identification scheme.
However this is an invalid URN, as there is no org namespace.

Proposed resolution methods:
Option A: Create a DASH-IF URN namespace. Submit an RFC for the purpose. This approach was taken by DVB, EBU, SMPTE, CableLabs, etc. 
Option B: Use DASH-IF URL for the purpose.

**Comment by haudiobe** [comment]
There is a third option using urn:dns ...

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf
