### ISSUE TITLE
@audioSamplingRate and AAC SBR

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/DASH-IF-IOP#66]
Received a question from implementers on value of @audioSamplingRate when SBR is used (i.e., whether @audioSamplingRate is core AAC sampling rate or SBR sampling rate in case they differ). It may be good to put an informative note.

**Comment by haudiobe** [comment]
Added to version 3.2 as published here: http://dashif.org/wp-content/uploads/2015/12/DASH-IF-IOP-v3.2.pdf
