### ISSUE TITLE
Figure 18 Bug

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#68]
Submitter: Kazuhiko Takabayashi
Email: kazuhiko.takabayashi@jp.sony.com
V3.1 (non-technical, but editorial)
Please correct Figure 18 "Visualization of box structure with key rotation".
As I pointed out earlier on the DASH+IOP reflecter, the figure illustrates the 'pssh' is contained in the 'traf' box while it is defined to be contained in the 'moof' box directly in ISO/IEC 23001-7.

**Comment by lpiron** [comment]
Agreed, attached the corrected figure.
[figure18.docx](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/files/104533/figure18.docx)

**Comment by haudiobe** [comment]
Closed => added to v3.21
