### ISSUE TITLE
Mistake in the Figure 18, section 7.4.1

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#71]
Submitter: Turmel
Email: rturmel@envivio.com
Hi,

In version 3.2 of the document, there is a mistake in the Figure 18, section 7.4.1 Box Hierarchy, the 'pssh' box should be contained in the 'moof' box as it is correctly described in the above text, and not 'traf' box.

Regards,
Richard Turmel

**Comment by lpiron** [comment]
Resolution given under https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/68

**Comment by haudiobe** [comment]
added to v3.21
