### ISSUE TITLE
Figure 12, the example for assetidentifer is wrong

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#72]
Submitter: Adithyan Ilangovan
Email: ilangovan@nomor.de
In Page 79, Section 5.3.4.1, Figure 12, the example for assetidentifer is wrong.

There are no closing tags for the asset identifier element (/AssetIdentifer).

The current version is : 

 
 <Period start="PT0.00S" duration="PT600.6S" id="movie period #1">
 <AssetIdentifier schemeIdUri="urn:org:dashif:asset-id:2013"
 value="md:cid:EIDR:10.5240%2f0EFB-02CD-126E-8092-1E49-W">

The correct version should be:

 
 <Period start="PT0.00S" duration="PT600.6S" id="movie period #1">
 <AssetIdentifier schemeIdUri="urn:org:dashif:asset-id:2013"
 value="md:cid:EIDR:10.5240%2f0EFB-02CD-126E-8092-1E49-W"></AssetIdentifer>

Please fix this.

**Comment by AdithyanIlangovan** [comment]
Sorry, the previous had comment had some styling problem. I am repeating it here.

In Page 79, Section 5.3.4.1, Figure 12, the example for assetidentifer is wrong.
There are no closing tags for the asset identifier element in the example shown in the figure.

The current version is :

    > <! -- Movie -->
    <Period start="PT0.00S" duration="PT600.6S" id="movie period #1">
    <AssetIdentifier schemeIdUri="urn:org:dashif:asset-id:2013"
    value="md:cid:EIDR:10.5240%2f0EFB-02CD-126E-8092-1E49-W">

The correct version should be :

    > <! -- Movie -->
    <Period start="PT0.00S" duration="PT600.6S" id="movie period #1">
    <AssetIdentifier schemeIdUri="urn:org:dashif:asset-id:2013"
    value="md:cid:EIDR:10.5240%2f0EFB-02CD-126E-8092-1E49-W"> </AssetIdentifier>

**Comment by haudiobe** [comment]
Add to v3.3

**Comment by haudiobe** [comment]
Added to v3.21
