### ISSUE TITLE
Permitted Attributes in Static Content

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#73]
Question for IOP group. When a player sees the following manifest, what should it do? It is static, yet it declares a AST and a timeShiftBufferDepth of 30s. It is obviously a formerly live service manifest which has been converted to VOD by changing only the type to static. Once the type is static, should a player ignore the AST and timeShiftBufferDepth parameters and assume that all segments are always available? 

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011” 
type=“static"
availabilityStartTime="2016-02-01T11:39:10Z”
mediaPresentationDuration=“PT5M"
minBufferTime=“PT10S"
timeShiftBufferDepth=“PT30S"
profiles="urn:mpeg:dash:profile:isoff-main:2011">
<Period>
…

**Comment by kilroyh** [comment]
Changing the MPD type to "static" should only mean the MPD won't be updated, i.e. the MPD won't expire, but the Segments might.

The timeShiftBufferDepth should not be ignored.  That and @AST indicate Segment availability for some wall clock time.  If a service is for instance contractually bound to only offer the content for a limited time, those Segments won't be available later.  If they are available for "catch up" or VOD access, a correct MPD should be offered.  It is common practice for the Segments of live streams to be offered as individual "shows" in new MPDs after all Segments are recorded (frequently called "live to VOD").  In that case, the timeShiftBufferDepth limitation is removed, and the first Segment explicitly identified by adjusting @AST or removing it and adding @duration to dissociate the presentation from wall clock time.  

In some cases, an association of the original wall clock time to presentation time may be useful to synchronize external presentation elements (e.g. twitter feed) that are timestamped in UTC.

**Comment by haudiobe** [comment]
addressed in v3.22
