### ISSUE TITLE
Example in in section 5.3.4.1

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#75]
Section 5.3.2.1 of ISO 23009-1:2014 states that the PeriodStart of each Period must be the PeriodStart plus the duration of the previous Period.
The example MPD in section 5.3.4.1 of
http://dashif.org/w/2015/04/DASH-IF-IOP-v3.0.pdf
contradicts this: the second Period (the mid-roll) has a PeriodStart of 60, even though the previous Period had a start of 0 and a duration of 600.6.

Is there something I'm missing?

Costin

**Comment by perses** [comment]
Actually, the problem is with the last Period.

**Comment by waqarz** [comment]
I would like to understand this in general (not just specific to the example in  DASH-IF IOP): It is clear that ISO/IEC 23009-1 3rd edition does NOT mandate "PeriodStart of each Period must be the PeriodStart plus the duration of the previous Period", as the text in Section 5.3.2.1 says:

"If (i) @duration attribute is present, and (ii) the next Period element contains a @start attribute or ..., then this Period is an Early Terminated Period"

For "Early Terminated Period", there is no mandate to have PeriodStart of the next period being equal to "PeriodStart plus the duration of the previous Period". The question is:

- Is there any conflict between 23009-1 3rd additions' interpretation above to DASH-IF IOP (the latter uses amendment 1 and cor.1, as well as well as Amendment 3 as reference)?
