### ISSUE TITLE
Trick mode in multi-track content

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/DASH-IF-IOP#79]
In 3.2.9. (Trick Mode Support), the @value of an Essential/Supplemental descriptor is AdaptationSet@id of the main content.
Can there be use cases where one trickmode adaptation set serves more than one main adaptation set (e.g. UHD and HD)?

**Comment by haudiobe** [comment]
Checked this one more time and this is what is already said: "annotate the Adaptation Set with an EssentialProperty descriptor or Supple-mentalProperty descriptor with URL "http://dashif.org/guidelines/trickmode" and the @value the value of @id attribute of the Adaptation Set to which these trick mode Representations belong. The trick mode Representations must be time-aligned with the Representations in the main Adaptation Set. _The value may also be a white-space separated list of @id values. In this case the trick mode Adaptation Set is associated to all Adaptation Sets with the values of the @id._"

**Comment by haudiobe** [comment]
Closed, no updates necessary
