### ISSUE TITLE
Profiles n HbbTV

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#81]
Dear all,

Having been dragged into debugging DASH inter-operability problems recently for my colleagues, I would like to ask a question here.

If someone implements a DVB-DASH player today, what @profile(s) must it ignore in order to preserve future ecosystem evolution? Specifically the concern here is DASH players that ignore the values of @profile and then break when confronted with something which they should not be playing. 

Here are some example @profiles with my thoughts in order to help make a discussion more concrete;

|  |  |  |
| --- | --- | --- |
| Value of AdaptationSet@profiles | Ignored by DVB-DASH player? | Comment |
| "urn:mpeg:dash:profile:isoff-on-demand:2011, http://dashif.org/guidelines/dash264" | ? | Not sure what this is supposed to mean. |
| "http://dashif.org/guidelines/dash264" | If a DVB-DASH player does not support DASH-IF then Adaptation Sets with this value for @profile must be ignored | If players attempt to play Adaptation Sets with this value of @profile and then fail then this could significantly constrain future ecosystem evolution |
| "urn:mpeg:dash:profile:isoff-on-demand:2011" | In theory should be ignored | We leave out enough of the MPEG on-demand profile that attempting to play it is dangerous. However this would not cause problems with future ecosystem evolution. |
| “urn:mpeg:dash:profile:isoff-live:2011” | In theory should be ignored | We include enough of the MPEG live profile that attempting to play it is probably safe. This would not cause problems with future ecosystem evolution. |
| "urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2014" | Must be supported |  |
| "urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2015" | Must be ignored | If existing players will attempt to play content explicitly labelled as needing a future version of DVB-DASH then this will be very constraining to the future evolution of our spec. |
| "urn:mpeg:dash:profile:isoff-on-demand:2014, http://dashif.org/guidelines/dash264, urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2014" | Must be supported |  |
| "http://dashif.org/guidelines/dash264, urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2014" | Must be supported |  |
| "urn:mpeg:dash:profile:isoff-on-demand:2014, urn:dvb:dash:profile:dvb-dash:isoff-ext-on-demand:2014" | Must be supported |  |
| "urn:hbbtv:dash:profile:isoff-live:2012" | In theory should be ignored by a DVB-DASH player not supporting the old HbbTV DASH profile | Attempting to play this would not harm future ecosystem evolution and it should play correctly. |

Once it's clear what the behaviour should be, we should see what the spec(s) require. MPEG defines a concept of a profile-specific MPD but how much of that is normative is not very clear to me. Particularly if a DASH player supports more than one profile.

Jon

**Comment by jpiesing** [comment]
Here are 1st drafts of the proposed test definitions for HbbTV DASH players that **do not** support DASH-IF. Comments are welcome but the deadline for concluding any discussion resulting from those comments is close of business Thursday in Europe. 
1) The src of an HTML5 video element points to a DASH MPD where the @profiles indicates only "http://dashif.org/guidelines/dash264". The MPD is rejected and a MEDIA_ERR_SRC_NOT_SUPPORTED error is generated.
2) The src of an HTML5 video element points to a DASH MPD where the @profiles indicates "http://dashif.org/guidelines/dash264" and "urn:dvb:dash:profile:dvb-dash:2014". The MPD includes Video, Audio and subtitle Adaptation Sets with @profiles "urn:dvb:dash:profile:dvb-dash:isoff-ext-live:2014", Video, Audio and subtitle Adaptation Sets with @profiles "http://dashif.org/guidelines/dash264" and Video, Audio and subtitle Adaptation Sets with both of these. When the load() method is called, no VideoTrack, AudioTrack or TextTrack objects are created for the Adaptation Sets where @profiles only contains "http://dashif.org/guidelines/dash264". 
3) The src of an HTML5 video element points to a DASH MPD where the @profiles indicates "http://dashif.org/guidelines/dash264" and "urn:dvb:dash:profile:dvb-dash:2014". The MPD includes one each of Video, Audio and subtitle Adaptation Sets with no @profiles element. Each Adaptation Set includes one or more Representations with @profiles set to "urn:dvb:dash:profile:dvb-dash:isoff-ext-live:2014", one or more Representations with @profiles set to "http://dashif.org/guidelines/dash264" and one or more representations with @profiles set to  both of these. When the play method is called on the video element, the Representations with @profiles set only to "http://dashif.org/guidelines/dash264" are not presented.

**Comment by haudiobe** [comment]
- still open, might need to be discussed at the f2f meeting if time permits

- Discussion:
- There are too many profiles
- We need to layer the issues on media, file format and DASH layer
- We do not do anything on the v3.3, but we create a task force to simplify the issue
- It is also related to the feature-based development as well as the multi-track issues
- Take into account the conformance software and test vectors as well
- Profiles should be clear packages with simple feature packages
(Iraj) Activity will be started: Iraj, Yuriy, Richard, Thomas

**Comment by irajs** [comment]
A new proposal to be discussed:  http://files.groupspaces.com/dashif/files/1919457/Signaling+profiles+and+Interop+Point-v2-20170221.pptx
