### ISSUE TITLE
HEVC Sync Sample Issue from MPEG

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#88]
HEVC Sync Samples: 29n15933.zip
[29n15933.zip](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/files/314467/29n15933.zip)

**Comment by waqarz** [comment]
As far as current DASH-IF HEVC test vectors are concerned, (several representations that I have checked) only use IDR pictures as sync samples.

**Comment by haudiobe** [comment]
done - checked by Waqar
