### ISSUE TITLE
DRM priority

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/DASH-IF-IOP#91]
In case of multiple DRMs supported by the DASH client there may be a case where the user prefers to use one DRM over the other for business reasons (e.g. one DRM can be more expensive)
We currently seem not have an ability to indicate a relative priority of a particular DRM.

**Comment by sandersaares** [comment]
I wonder if this decision might be best left to the client application instead? After all, the prioritization of DRM systems is likely to also be dependent on what device the content is used on. In my view, it would serve DASH best to be agnostic of DRM specifics and focus on encryption in the abstract instead.

See also https://github.com/Dash-Industry-Forum/dash.js/issues/1367 for thoughts on how this might be seen from a player perspective.
