### ISSUE TITLE
Clarify Subsegments with Segment Index conformance points

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#95]
Clarify conformance points in Section 3.2.1: 

> Subsegments with Segment Index. In this case either the @indexRange attribute shall be present or the RepresentationIndex element shall be present. Only a single sidx box shall be present

How is the "case" above signaled? It should say instead:

> Indexed Media Segment: In this case either the @indexRange attribute shall be present ...

That will clarify that the signalling is "msix" compatibility brand. Conformance needs to be implemented for this case: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/146

**Comment by haudiobe** [comment]
Add reference to MPEG specification for Index Media Segment and apply above proposal.

**Comment by haudiobe** [comment]
added to version 3.32
