### ISSUE TITLE
urn:mpeg:dash:utc:direct:2014 is missing from the list

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#99]
Is there any reason that the direct utc has not been listed in DASH-IF  IOP 4.7.2?

 The MPD should contain at least one UTCTiming element with @schemeIdURI set to 
 one of the following: 
 o urn:mpeg:dash:utc:ntp:2014 
 o urn:mpeg:dash:utc:http-head:2014 
 o urn:mpeg:dash:utc:http-xsdate:2014
 o urn:mpeg:dash:utc:http-iso:2014 20
 o urn:mpeg:dash:utc:http-ntp:2014

urn:mpeg:dash:utc:direct:2014 is missing.

**Comment by haudiobe** [comment]
Will not add it! It is an omission, but document that careful usage by service provider if MPDs are cached.
